import { useState, useMemo } from 'react';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import Dialog from '@mui/material/Dialog';
import DialogTitle from '@mui/material/DialogTitle';
import DialogContent from '@mui/material/DialogContent';
import DialogActions from '@mui/material/DialogActions';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemButton from '@mui/material/ListItemButton';
import ListItemIcon from '@mui/material/ListItemIcon';
import ListItemText from '@mui/material/ListItemText';
import Checkbox from '@mui/material/Checkbox';
import Divider from '@mui/material/Divider';
import CircularProgress from '@mui/material/CircularProgress';
import FolderZipIcon from '@mui/icons-material/FolderZip';
import InsertDriveFileIcon from '@mui/icons-material/InsertDriveFile';
import DataObjectIcon from '@mui/icons-material/DataObject';
import DownloadIcon from '@mui/icons-material/Download';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { useMapStore } from '../../store/mapStore';
import {
  generateAllFiles,
  generateConfigJson,
  type GeneratedFile,
} from '../../generators/codeGenerator';
import type { MapState } from '../../types';

interface ExportDialogProps {
  open: boolean;
  onClose: () => void;
}

type ExportMode = 'project' | 'files' | 'json';

export default function ExportDialog({ open, onClose }: ExportDialogProps) {
  const [mode, setMode] = useState<ExportMode>('project');
  const [selectedFiles, setSelectedFiles] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);

  // Select individual state slices to avoid infinite loop
  const map = useMapStore((s) => s.map);
  const layers = useMapStore((s) => s.layers);
  const widgets = useMapStore((s) => s.widgets);
  const graphics = useMapStore((s) => s.graphics);
  const popupTemplates = useMapStore((s) => s.popupTemplates);
  const jsonDataLayers = useMapStore((s) => s.jsonDataLayers);

  // Memoize the state object
  const state = useMemo<MapState>(
    () => ({ map, layers, widgets, graphics, popupTemplates, jsonDataLayers }),
    [map, layers, widgets, graphics, popupTemplates, jsonDataLayers]
  );

  const files = useMemo(() => generateAllFiles(state), [state]);

  const handleToggleFile = (fileName: string) => {
    setSelectedFiles((prev) =>
      prev.includes(fileName)
        ? prev.filter((f) => f !== fileName)
        : [...prev, fileName]
    );
  };

  const handleSelectAll = () => {
    if (selectedFiles.length === files.length) {
      setSelectedFiles([]);
    } else {
      setSelectedFiles(files.map((f) => f.name));
    }
  };

  const handleExportProject = async () => {
    setLoading(true);
    try {
      const zip = new JSZip();

      files.forEach((file) => {
        const fullPath = file.path + file.name;
        zip.file(fullPath, file.content);
      });

      // Add README
      zip.file(
        'README.md',
        `# ArcGIS React Map

This project was generated by ArcGIS React Builder.

## Getting Started

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Start the development server:
   \`\`\`bash
   npm run dev
   \`\`\`

3. Build for production:
   \`\`\`bash
   npm run build
   \`\`\`

## Configuration

The map configuration is stored in \`map-config.json\`. You can modify this file and regenerate the code.

## Generated Files

- \`src/ArcGISMap.tsx\` - Main map component
- \`src/App.tsx\` - App wrapper component
- \`src/main.tsx\` - Entry point
- \`src/index.css\` - Base styles
- \`map-config.json\` - Map configuration

## Dependencies

- React 18
- @arcgis/core (ArcGIS JS API 4.x)
- Vite
- TypeScript
`
      );

      const blob = await zip.generateAsync({ type: 'blob' });
      saveAs(blob, 'arcgis-react-map.zip');
    } finally {
      setLoading(false);
      onClose();
    }
  };

  const handleExportFiles = async () => {
    setLoading(true);
    try {
      const zip = new JSZip();

      files
        .filter((f) => selectedFiles.includes(f.name))
        .forEach((file) => {
          zip.file(file.name, file.content);
        });

      const blob = await zip.generateAsync({ type: 'blob' });
      saveAs(blob, 'arcgis-files.zip');
    } finally {
      setLoading(false);
      onClose();
    }
  };

  const handleExportJson = () => {
    const json = generateConfigJson(state);
    const blob = new Blob([json], { type: 'application/json' });
    saveAs(blob, 'map-config.json');
    onClose();
  };

  const handleDownloadSingleFile = (file: GeneratedFile) => {
    const blob = new Blob([file.content], { type: 'text/plain' });
    saveAs(blob, file.name);
  };

  return (
    <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
      <DialogTitle>Export Project</DialogTitle>
      <DialogContent>
        <Box sx={{ display: 'flex', gap: 1, mb: 2 }}>
          <Button
            variant={mode === 'project' ? 'contained' : 'outlined'}
            onClick={() => setMode('project')}
            startIcon={<FolderZipIcon />}
            size="small"
          >
            Full Project
          </Button>
          <Button
            variant={mode === 'files' ? 'contained' : 'outlined'}
            onClick={() => setMode('files')}
            startIcon={<InsertDriveFileIcon />}
            size="small"
          >
            Select Files
          </Button>
          <Button
            variant={mode === 'json' ? 'contained' : 'outlined'}
            onClick={() => setMode('json')}
            startIcon={<DataObjectIcon />}
            size="small"
          >
            Config Only
          </Button>
        </Box>

        <Divider sx={{ my: 2 }} />

        {mode === 'project' && (
          <Box>
            <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
              Export a complete React project with all necessary files ready to run.
            </Typography>
            <Typography variant="caption" color="text.secondary">
              Includes:
            </Typography>
            <List dense>
              {files.map((file) => (
                <ListItem key={file.name} dense>
                  <ListItemIcon sx={{ minWidth: 36 }}>
                    <InsertDriveFileIcon fontSize="small" />
                  </ListItemIcon>
                  <ListItemText
                    primary={file.name}
                    secondary={file.path || '/'}
                    primaryTypographyProps={{ variant: 'body2' }}
                    secondaryTypographyProps={{ variant: 'caption' }}
                  />
                </ListItem>
              ))}
            </List>
          </Box>
        )}

        {mode === 'files' && (
          <Box>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
              <Typography variant="body2" color="text.secondary">
                Select files to export:
              </Typography>
              <Button size="small" onClick={handleSelectAll}>
                {selectedFiles.length === files.length ? 'Deselect All' : 'Select All'}
              </Button>
            </Box>
            <List dense>
              {files.map((file) => (
                <ListItem key={file.name} disablePadding>
                  <ListItemButton
                    dense
                    onClick={() => handleToggleFile(file.name)}
                  >
                    <ListItemIcon sx={{ minWidth: 36 }}>
                      <Checkbox
                        edge="start"
                        checked={selectedFiles.includes(file.name)}
                        size="small"
                      />
                    </ListItemIcon>
                    <ListItemText
                      primary={file.name}
                      primaryTypographyProps={{ variant: 'body2' }}
                    />
                    <Button
                      size="small"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleDownloadSingleFile(file);
                      }}
                    >
                      <DownloadIcon fontSize="small" />
                    </Button>
                  </ListItemButton>
                </ListItem>
              ))}
            </List>
          </Box>
        )}

        {mode === 'json' && (
          <Box>
            <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
              Export only the map configuration as JSON. This can be imported later
              to regenerate the code.
            </Typography>
            <Box
              sx={{
                p: 2,
                bgcolor: 'rgba(0,0,0,0.3)',
                borderRadius: 1,
                maxHeight: 200,
                overflow: 'auto',
                fontFamily: 'monospace',
                fontSize: 11,
              }}
            >
              <pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>
                {generateConfigJson(state)}
              </pre>
            </Box>
          </Box>
        )}
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose}>Cancel</Button>
        {mode === 'project' && (
          <Button
            onClick={handleExportProject}
            variant="contained"
            disabled={loading}
            startIcon={loading ? <CircularProgress size={16} /> : <FolderZipIcon />}
          >
            Export Project
          </Button>
        )}
        {mode === 'files' && (
          <Button
            onClick={handleExportFiles}
            variant="contained"
            disabled={loading || selectedFiles.length === 0}
            startIcon={loading ? <CircularProgress size={16} /> : <DownloadIcon />}
          >
            Export Selected ({selectedFiles.length})
          </Button>
        )}
        {mode === 'json' && (
          <Button
            onClick={handleExportJson}
            variant="contained"
            startIcon={<DataObjectIcon />}
          >
            Download JSON
          </Button>
        )}
      </DialogActions>
    </Dialog>
  );
}
