import type { ComponentDefinition, PropDefinition } from '../types';

// Common prop definitions that can be reused
const commonStyleProps: PropDefinition[] = [
  { name: 'customStyles.width', type: 'dimension', label: 'Width', group: 'style' },
  { name: 'customStyles.height', type: 'dimension', label: 'Height', group: 'style' },
  { name: 'customStyles.minWidth', type: 'dimension', label: 'Min Width', group: 'style' },
  { name: 'customStyles.maxWidth', type: 'dimension', label: 'Max Width', group: 'style' },
  { name: 'customStyles.minHeight', type: 'dimension', label: 'Min Height', group: 'style' },
  { name: 'customStyles.maxHeight', type: 'dimension', label: 'Max Height', group: 'style' },
  { name: 'customStyles.backgroundColor', type: 'backgroundColor', label: 'Background', group: 'style' },
  { name: 'customStyles.color', type: 'color', label: 'Text Color', group: 'style' },
  { name: 'customStyles.borderRadius', type: 'dimension', label: 'Border Radius', group: 'style' },
  { name: 'customStyles.borderWidth', type: 'dimension', label: 'Border Width', group: 'style' },
  { name: 'customStyles.borderStyle', type: 'select', label: 'Border Style', options: ['none', 'solid', 'dashed', 'dotted', 'double'], group: 'style' },
  { name: 'customStyles.borderColor', type: 'color', label: 'Border Color', group: 'style' },
  { name: 'customStyles.opacity', type: 'slider', label: 'Opacity', min: 0, max: 1, step: 0.1, group: 'style' },
  { name: 'customStyles.boxShadow', type: 'select', label: 'Shadow', options: ['none', '0 1px 3px rgba(0,0,0,0.12)', '0 4px 6px rgba(0,0,0,0.1)', '0 10px 15px rgba(0,0,0,0.1)', '0 20px 25px rgba(0,0,0,0.15)'], group: 'style' },
];

const commonSpacingProps: PropDefinition[] = [
  { name: 'customStyles.padding', type: 'spacing', label: 'Padding', group: 'layout' },
  { name: 'customStyles.paddingTop', type: 'spacing', label: 'Padding Top', group: 'layout' },
  { name: 'customStyles.paddingRight', type: 'spacing', label: 'Padding Right', group: 'layout' },
  { name: 'customStyles.paddingBottom', type: 'spacing', label: 'Padding Bottom', group: 'layout' },
  { name: 'customStyles.paddingLeft', type: 'spacing', label: 'Padding Left', group: 'layout' },
  { name: 'customStyles.margin', type: 'spacing', label: 'Margin', group: 'layout' },
  { name: 'customStyles.marginTop', type: 'spacing', label: 'Margin Top', group: 'layout' },
  { name: 'customStyles.marginRight', type: 'spacing', label: 'Margin Right', group: 'layout' },
  { name: 'customStyles.marginBottom', type: 'spacing', label: 'Margin Bottom', group: 'layout' },
  { name: 'customStyles.marginLeft', type: 'spacing', label: 'Margin Left', group: 'layout' },
];

const commonLayoutProps: PropDefinition[] = [
  { name: 'customStyles.display', type: 'select', label: 'Display', options: ['block', 'flex', 'inline-flex', 'grid', 'inline', 'inline-block', 'none'], group: 'layout' },
  { name: 'customStyles.flexDirection', type: 'select', label: 'Flex Direction', options: ['row', 'row-reverse', 'column', 'column-reverse'], group: 'layout' },
  { name: 'customStyles.justifyContent', type: 'select', label: 'Justify Content', options: ['flex-start', 'center', 'flex-end', 'space-between', 'space-around', 'space-evenly'], group: 'layout' },
  { name: 'customStyles.alignItems', type: 'select', label: 'Align Items', options: ['flex-start', 'center', 'flex-end', 'stretch', 'baseline'], group: 'layout' },
  { name: 'customStyles.gap', type: 'spacing', label: 'Gap', group: 'layout' },
  { name: 'customStyles.flexWrap', type: 'select', label: 'Flex Wrap', options: ['nowrap', 'wrap', 'wrap-reverse'], group: 'layout' },
  { name: 'customStyles.overflow', type: 'select', label: 'Overflow', options: ['visible', 'hidden', 'scroll', 'auto'], group: 'layout' },
];

const commonAdvancedProps: PropDefinition[] = [
  { name: 'customId', type: 'string', label: 'Custom ID', group: 'advanced' },
  { name: 'customName', type: 'string', label: 'Component Name', group: 'advanced' },
  { name: 'customClassName', type: 'string', label: 'CSS Class', group: 'advanced' },
  { name: 'sx', type: 'sx', label: 'Custom Styles (sx)', group: 'advanced' },
];

export const componentDefinitions: ComponentDefinition[] = [
  // Input Components
  {
    type: 'Button',
    label: 'Button',
    category: 'inputs',
    description: 'Clickable button with various styles',
    defaultProps: {
      variant: 'contained',
      color: 'primary',
      children: 'Button',
    },
    availableProps: [
      { name: 'children', type: 'string', label: 'Text', group: 'basic' },
      { name: 'variant', type: 'select', label: 'Variant', options: ['contained', 'outlined', 'text'], group: 'basic' },
      { name: 'color', type: 'select', label: 'Color', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success', 'inherit'], group: 'basic' },
      { name: 'size', type: 'select', label: 'Size', options: ['small', 'medium', 'large'], group: 'basic' },
      { name: 'disabled', type: 'boolean', label: 'Disabled', group: 'basic' },
      { name: 'fullWidth', type: 'boolean', label: 'Full Width', group: 'basic' },
      { name: 'startIcon', type: 'icon', label: 'Start Icon', group: 'basic' },
      { name: 'endIcon', type: 'icon', label: 'End Icon', group: 'basic' },
      { name: 'disableElevation', type: 'boolean', label: 'Disable Elevation', group: 'basic' },
      { name: 'disableRipple', type: 'boolean', label: 'Disable Ripple', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
    acceptsChildren: ['Checkbox', 'Switch', 'IconButton', 'Avatar', 'Badge'],
  },
  {
    type: 'TextField',
    label: 'Text Field',
    category: 'inputs',
    description: 'Text input field with label',
    defaultProps: {
      label: 'Label',
      variant: 'outlined',
    },
    availableProps: [
      { name: 'label', type: 'string', label: 'Label', group: 'basic' },
      { name: 'placeholder', type: 'string', label: 'Placeholder', group: 'basic' },
      { name: 'defaultValue', type: 'string', label: 'Default Value', group: 'basic' },
      { name: 'helperText', type: 'string', label: 'Helper Text', group: 'basic' },
      { name: 'variant', type: 'select', label: 'Variant', options: ['outlined', 'filled', 'standard'], group: 'basic' },
      { name: 'size', type: 'select', label: 'Size', options: ['small', 'medium'], group: 'basic' },
      { name: 'type', type: 'select', label: 'Type', options: ['text', 'password', 'email', 'number', 'tel', 'url', 'search', 'date', 'time', 'datetime-local'], group: 'basic' },
      { name: 'disabled', type: 'boolean', label: 'Disabled', group: 'basic' },
      { name: 'required', type: 'boolean', label: 'Required', group: 'basic' },
      { name: 'error', type: 'boolean', label: 'Error State', group: 'basic' },
      { name: 'fullWidth', type: 'boolean', label: 'Full Width', group: 'basic' },
      { name: 'multiline', type: 'boolean', label: 'Multiline', group: 'basic' },
      { name: 'rows', type: 'number', label: 'Rows', group: 'basic' },
      { name: 'maxRows', type: 'number', label: 'Max Rows', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },
  {
    type: 'Select',
    label: 'Select',
    category: 'inputs',
    description: 'Dropdown selection field',
    defaultProps: {
      label: 'Select',
      variant: 'outlined',
      options: ['Option 1', 'Option 2', 'Option 3'],
    },
    availableProps: [
      { name: 'label', type: 'string', label: 'Label', group: 'basic' },
      { name: 'options', type: 'options', label: 'Options', group: 'basic' },
      { name: 'defaultValue', type: 'string', label: 'Default Value', group: 'basic' },
      { name: 'variant', type: 'select', label: 'Variant', options: ['outlined', 'filled', 'standard'], group: 'basic' },
      { name: 'size', type: 'select', label: 'Size', options: ['small', 'medium'], group: 'basic' },
      { name: 'disabled', type: 'boolean', label: 'Disabled', group: 'basic' },
      { name: 'fullWidth', type: 'boolean', label: 'Full Width', group: 'basic' },
      { name: 'multiple', type: 'boolean', label: 'Multiple Selection', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },
  {
    type: 'Checkbox',
    label: 'Checkbox',
    category: 'inputs',
    description: 'Checkbox input',
    defaultProps: {
      defaultChecked: false,
      label: 'Checkbox',
    },
    availableProps: [
      { name: 'label', type: 'string', label: 'Label', group: 'basic' },
      { name: 'defaultChecked', type: 'boolean', label: 'Checked', group: 'basic' },
      { name: 'color', type: 'select', label: 'Color', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success', 'default'], group: 'basic' },
      { name: 'size', type: 'select', label: 'Size', options: ['small', 'medium', 'large'], group: 'basic' },
      { name: 'disabled', type: 'boolean', label: 'Disabled', group: 'basic' },
      { name: 'indeterminate', type: 'boolean', label: 'Indeterminate', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },
  {
    type: 'Switch',
    label: 'Switch',
    category: 'inputs',
    description: 'Toggle switch',
    defaultProps: {
      defaultChecked: false,
      label: 'Switch',
    },
    availableProps: [
      { name: 'label', type: 'string', label: 'Label', group: 'basic' },
      { name: 'defaultChecked', type: 'boolean', label: 'Checked', group: 'basic' },
      { name: 'color', type: 'select', label: 'Color', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success', 'default'], group: 'basic' },
      { name: 'size', type: 'select', label: 'Size', options: ['small', 'medium'], group: 'basic' },
      { name: 'disabled', type: 'boolean', label: 'Disabled', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },
  {
    type: 'Slider',
    label: 'Slider',
    category: 'inputs',
    description: 'Range slider input',
    defaultProps: {
      defaultValue: 50,
      min: 0,
      max: 100,
    },
    availableProps: [
      { name: 'defaultValue', type: 'number', label: 'Default Value', group: 'basic' },
      { name: 'min', type: 'number', label: 'Min', group: 'basic' },
      { name: 'max', type: 'number', label: 'Max', group: 'basic' },
      { name: 'step', type: 'number', label: 'Step', group: 'basic' },
      { name: 'marks', type: 'boolean', label: 'Show Marks', group: 'basic' },
      { name: 'valueLabelDisplay', type: 'select', label: 'Value Label', options: ['auto', 'on', 'off'], group: 'basic' },
      { name: 'color', type: 'select', label: 'Color', options: ['primary', 'secondary'], group: 'basic' },
      { name: 'size', type: 'select', label: 'Size', options: ['small', 'medium'], group: 'basic' },
      { name: 'disabled', type: 'boolean', label: 'Disabled', group: 'basic' },
      { name: 'orientation', type: 'select', label: 'Orientation', options: ['horizontal', 'vertical'], group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },
  {
    type: 'Rating',
    label: 'Rating',
    category: 'inputs',
    description: 'Star rating input',
    defaultProps: {
      defaultValue: 3,
      max: 5,
    },
    availableProps: [
      { name: 'defaultValue', type: 'number', label: 'Default Value', group: 'basic' },
      { name: 'max', type: 'number', label: 'Max Stars', group: 'basic' },
      { name: 'precision', type: 'select', label: 'Precision', options: ['0.5', '1'], group: 'basic' },
      { name: 'size', type: 'select', label: 'Size', options: ['small', 'medium', 'large'], group: 'basic' },
      { name: 'disabled', type: 'boolean', label: 'Disabled', group: 'basic' },
      { name: 'readOnly', type: 'boolean', label: 'Read Only', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },
  {
    type: 'Radio',
    label: 'Radio Button',
    category: 'inputs',
    description: 'Radio button input',
    defaultProps: {
      label: 'Radio',
    },
    availableProps: [
      { name: 'label', type: 'string', label: 'Label', group: 'basic' },
      { name: 'value', type: 'string', label: 'Value', group: 'basic' },
      { name: 'color', type: 'select', label: 'Color', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success', 'default'], group: 'basic' },
      { name: 'size', type: 'select', label: 'Size', options: ['small', 'medium'], group: 'basic' },
      { name: 'disabled', type: 'boolean', label: 'Disabled', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },
  {
    type: 'RadioGroup',
    label: 'Radio Group',
    category: 'inputs',
    description: 'Group of radio buttons',
    defaultProps: {
      row: false,
    },
    availableProps: [
      { name: 'defaultValue', type: 'string', label: 'Default Value', group: 'basic' },
      { name: 'row', type: 'boolean', label: 'Horizontal Layout', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
    acceptsChildren: ['Radio', 'FormControlLabel'],
  },

  // Layout Components
  {
    type: 'Box',
    label: 'Box',
    category: 'layout',
    description: 'Flexible container element',
    defaultProps: {
      customStyles: {
        padding: '16px',
        minHeight: '50px',
        display: 'flex',
        flexDirection: 'column',
      },
    },
    availableProps: [
      { name: 'component', type: 'select', label: 'HTML Element', options: ['div', 'span', 'section', 'article', 'main', 'aside', 'header', 'footer', 'nav'], group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonLayoutProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
  },
  {
    type: 'Stack',
    label: 'Stack',
    category: 'layout',
    description: 'Stack items vertically or horizontally',
    defaultProps: {
      direction: 'column',
      spacing: 2,
    },
    availableProps: [
      { name: 'direction', type: 'select', label: 'Direction', options: ['row', 'row-reverse', 'column', 'column-reverse'], group: 'basic' },
      { name: 'spacing', type: 'number', label: 'Spacing', group: 'basic' },
      { name: 'divider', type: 'boolean', label: 'Show Dividers', group: 'basic' },
      { name: 'justifyContent', type: 'select', label: 'Justify Content', options: ['flex-start', 'center', 'flex-end', 'space-between', 'space-around', 'space-evenly'], group: 'layout' },
      { name: 'alignItems', type: 'select', label: 'Align Items', options: ['flex-start', 'center', 'flex-end', 'stretch', 'baseline'], group: 'layout' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
  },
  {
    type: 'Grid',
    label: 'Grid Container',
    category: 'layout',
    description: 'Responsive grid container',
    defaultProps: {
      container: true,
      spacing: 2,
    },
    availableProps: [
      { name: 'container', type: 'boolean', label: 'Container', group: 'basic' },
      { name: 'spacing', type: 'number', label: 'Spacing', group: 'basic' },
      { name: 'columns', type: 'number', label: 'Columns', group: 'basic' },
      { name: 'direction', type: 'select', label: 'Direction', options: ['row', 'row-reverse', 'column', 'column-reverse'], group: 'basic' },
      { name: 'justifyContent', type: 'select', label: 'Justify Content', options: ['flex-start', 'center', 'flex-end', 'space-between', 'space-around', 'space-evenly'], group: 'layout' },
      { name: 'alignItems', type: 'select', label: 'Align Items', options: ['flex-start', 'center', 'flex-end', 'stretch', 'baseline'], group: 'layout' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
    acceptsChildren: ['GridItem', 'Box', 'Paper', 'Card'],
  },
  {
    type: 'GridItem',
    label: 'Grid Item',
    category: 'layout',
    description: 'Grid item with responsive sizes',
    defaultProps: {
      xs: 12,
      sm: 6,
      md: 4,
    },
    availableProps: [
      { name: 'xs', type: 'number', label: 'XS (0-600px)', group: 'basic', min: 1, max: 12 },
      { name: 'sm', type: 'number', label: 'SM (600-900px)', group: 'basic', min: 1, max: 12 },
      { name: 'md', type: 'number', label: 'MD (900-1200px)', group: 'basic', min: 1, max: 12 },
      { name: 'lg', type: 'number', label: 'LG (1200-1536px)', group: 'basic', min: 1, max: 12 },
      { name: 'xl', type: 'number', label: 'XL (1536px+)', group: 'basic', min: 1, max: 12 },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
  },
  {
    type: 'Container',
    label: 'Container',
    category: 'layout',
    description: 'Centered container with max-width',
    defaultProps: {
      maxWidth: 'lg',
    },
    availableProps: [
      { name: 'maxWidth', type: 'select', label: 'Max Width', options: ['xs', 'sm', 'md', 'lg', 'xl', 'false'], group: 'basic' },
      { name: 'fixed', type: 'boolean', label: 'Fixed Width', group: 'basic' },
      { name: 'disableGutters', type: 'boolean', label: 'Disable Gutters', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
  },
  {
    type: 'Card',
    label: 'Card',
    category: 'surfaces',
    description: 'Card container for content',
    defaultProps: {
      variant: 'elevation',
      customStyles: { padding: '16px', minWidth: '200px' },
    },
    availableProps: [
      { name: 'variant', type: 'select', label: 'Variant', options: ['elevation', 'outlined'], group: 'basic' },
      { name: 'raised', type: 'boolean', label: 'Raised', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
  },
  {
    type: 'Paper',
    label: 'Paper',
    category: 'surfaces',
    description: 'Surface with elevation',
    defaultProps: {
      elevation: 1,
      customStyles: { padding: '16px' },
    },
    availableProps: [
      { name: 'elevation', type: 'slider', label: 'Elevation', min: 0, max: 24, step: 1, group: 'basic' },
      { name: 'variant', type: 'select', label: 'Variant', options: ['elevation', 'outlined'], group: 'basic' },
      { name: 'square', type: 'boolean', label: 'Square', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
  },
  {
    type: 'Divider',
    label: 'Divider',
    category: 'layout',
    description: 'Visual divider line',
    defaultProps: {},
    availableProps: [
      { name: 'variant', type: 'select', label: 'Variant', options: ['fullWidth', 'inset', 'middle'], group: 'basic' },
      { name: 'orientation', type: 'select', label: 'Orientation', options: ['horizontal', 'vertical'], group: 'basic' },
      { name: 'textAlign', type: 'select', label: 'Text Align', options: ['center', 'left', 'right'], group: 'basic' },
      { name: 'children', type: 'string', label: 'Text', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },

  // Display Components
  {
    type: 'Typography',
    label: 'Typography',
    category: 'display',
    description: 'Text display with various styles',
    defaultProps: {
      variant: 'body1',
      children: 'Text content',
    },
    availableProps: [
      { name: 'children', type: 'string', label: 'Text', group: 'basic' },
      { name: 'variant', type: 'select', label: 'Variant', options: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'subtitle1', 'subtitle2', 'body1', 'body2', 'caption', 'overline', 'button'], group: 'basic' },
      { name: 'color', type: 'select', label: 'Color', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success', 'textPrimary', 'textSecondary', 'textDisabled'], group: 'basic' },
      { name: 'align', type: 'select', label: 'Align', options: ['left', 'center', 'right', 'justify'], group: 'basic' },
      { name: 'gutterBottom', type: 'boolean', label: 'Gutter Bottom', group: 'basic' },
      { name: 'noWrap', type: 'boolean', label: 'No Wrap', group: 'basic' },
      { name: 'paragraph', type: 'boolean', label: 'Paragraph', group: 'basic' },
      { name: 'customStyles.fontWeight', type: 'select', label: 'Font Weight', options: ['300', '400', '500', '600', '700', '800', '900'], group: 'style' },
      { name: 'customStyles.fontSize', type: 'dimension', label: 'Font Size', group: 'style' },
      { name: 'customStyles.lineHeight', type: 'dimension', label: 'Line Height', group: 'style' },
      { name: 'customStyles.letterSpacing', type: 'dimension', label: 'Letter Spacing', group: 'style' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },
  {
    type: 'Avatar',
    label: 'Avatar',
    category: 'display',
    description: 'User avatar or icon',
    defaultProps: {
      children: 'A',
    },
    availableProps: [
      { name: 'children', type: 'string', label: 'Text', group: 'basic' },
      { name: 'src', type: 'string', label: 'Image URL', group: 'basic' },
      { name: 'alt', type: 'string', label: 'Alt Text', group: 'basic' },
      { name: 'variant', type: 'select', label: 'Variant', options: ['circular', 'rounded', 'square'], group: 'basic' },
      { name: 'customStyles.width', type: 'dimension', label: 'Width', group: 'style' },
      { name: 'customStyles.height', type: 'dimension', label: 'Height', group: 'style' },
      { name: 'customStyles.backgroundColor', type: 'backgroundColor', label: 'Background', group: 'style' },
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },
  {
    type: 'Chip',
    label: 'Chip',
    category: 'display',
    description: 'Compact element for tags or choices',
    defaultProps: {
      label: 'Chip',
    },
    availableProps: [
      { name: 'label', type: 'string', label: 'Label', group: 'basic' },
      { name: 'variant', type: 'select', label: 'Variant', options: ['filled', 'outlined'], group: 'basic' },
      { name: 'color', type: 'select', label: 'Color', options: ['default', 'primary', 'secondary', 'error', 'warning', 'info', 'success'], group: 'basic' },
      { name: 'size', type: 'select', label: 'Size', options: ['small', 'medium'], group: 'basic' },
      { name: 'clickable', type: 'boolean', label: 'Clickable', group: 'basic' },
      { name: 'disabled', type: 'boolean', label: 'Disabled', group: 'basic' },
      { name: 'onDelete', type: 'boolean', label: 'Show Delete', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },
  {
    type: 'Badge',
    label: 'Badge',
    category: 'display',
    description: 'Badge for notifications',
    defaultProps: {
      badgeContent: 4,
      color: 'primary',
    },
    availableProps: [
      { name: 'badgeContent', type: 'string', label: 'Content', group: 'basic' },
      { name: 'color', type: 'select', label: 'Color', options: ['default', 'primary', 'secondary', 'error', 'warning', 'info', 'success'], group: 'basic' },
      { name: 'variant', type: 'select', label: 'Variant', options: ['standard', 'dot'], group: 'basic' },
      { name: 'max', type: 'number', label: 'Max', group: 'basic' },
      { name: 'showZero', type: 'boolean', label: 'Show Zero', group: 'basic' },
      { name: 'invisible', type: 'boolean', label: 'Invisible', group: 'basic' },
      { name: 'overlap', type: 'select', label: 'Overlap', options: ['rectangular', 'circular'], group: 'basic' },
      { name: 'anchorOrigin.vertical', type: 'select', label: 'Vertical Position', options: ['top', 'bottom'], group: 'layout' },
      { name: 'anchorOrigin.horizontal', type: 'select', label: 'Horizontal Position', options: ['left', 'right'], group: 'layout' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
  },
  {
    type: 'Alert',
    label: 'Alert',
    category: 'feedback',
    description: 'Alert message display',
    defaultProps: {
      severity: 'info',
      children: 'This is an alert message',
    },
    availableProps: [
      { name: 'children', type: 'string', label: 'Message', group: 'basic' },
      { name: 'severity', type: 'select', label: 'Severity', options: ['error', 'warning', 'info', 'success'], group: 'basic' },
      { name: 'variant', type: 'select', label: 'Variant', options: ['standard', 'filled', 'outlined'], group: 'basic' },
      { name: 'title', type: 'string', label: 'Title', group: 'basic' },
      { name: 'icon', type: 'boolean', label: 'Show Icon', group: 'basic' },
      { name: 'onClose', type: 'boolean', label: 'Show Close', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },
  {
    type: 'LinearProgress',
    label: 'Linear Progress',
    category: 'feedback',
    description: 'Linear progress indicator',
    defaultProps: {
      variant: 'determinate',
      value: 50,
    },
    availableProps: [
      { name: 'variant', type: 'select', label: 'Variant', options: ['determinate', 'indeterminate', 'buffer', 'query'], group: 'basic' },
      { name: 'value', type: 'slider', label: 'Value', min: 0, max: 100, step: 1, group: 'basic' },
      { name: 'color', type: 'select', label: 'Color', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success', 'inherit'], group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },
  {
    type: 'CircularProgress',
    label: 'Circular Progress',
    category: 'feedback',
    description: 'Circular progress indicator',
    defaultProps: {
      variant: 'indeterminate',
    },
    availableProps: [
      { name: 'variant', type: 'select', label: 'Variant', options: ['determinate', 'indeterminate'], group: 'basic' },
      { name: 'value', type: 'slider', label: 'Value', min: 0, max: 100, step: 1, group: 'basic' },
      { name: 'size', type: 'dimension', label: 'Size', group: 'basic' },
      { name: 'thickness', type: 'number', label: 'Thickness', group: 'basic' },
      { name: 'color', type: 'select', label: 'Color', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success', 'inherit'], group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },
  {
    type: 'Skeleton',
    label: 'Skeleton',
    category: 'feedback',
    description: 'Loading placeholder',
    defaultProps: {
      variant: 'rectangular',
      width: 200,
      height: 100,
    },
    availableProps: [
      { name: 'variant', type: 'select', label: 'Variant', options: ['text', 'circular', 'rectangular', 'rounded'], group: 'basic' },
      { name: 'width', type: 'dimension', label: 'Width', group: 'basic' },
      { name: 'height', type: 'dimension', label: 'Height', group: 'basic' },
      { name: 'animation', type: 'select', label: 'Animation', options: ['pulse', 'wave', 'false'], group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },
  {
    type: 'Table',
    label: 'Table',
    category: 'data',
    description: 'Data table',
    defaultProps: {
      size: 'medium',
    },
    availableProps: [
      { name: 'size', type: 'select', label: 'Size', options: ['small', 'medium'], group: 'basic' },
      { name: 'stickyHeader', type: 'boolean', label: 'Sticky Header', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
  },
  {
    type: 'List',
    label: 'List',
    category: 'display',
    description: 'List container',
    defaultProps: {},
    availableProps: [
      { name: 'dense', type: 'boolean', label: 'Dense', group: 'basic' },
      { name: 'disablePadding', type: 'boolean', label: 'Disable Padding', group: 'basic' },
      { name: 'subheader', type: 'string', label: 'Subheader', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
    acceptsChildren: ['ListItem'],
  },
  {
    type: 'ListItem',
    label: 'List Item',
    category: 'display',
    description: 'List item with text',
    defaultProps: {
      primaryText: 'List Item',
    },
    availableProps: [
      { name: 'primaryText', type: 'string', label: 'Primary Text', group: 'basic' },
      { name: 'secondaryText', type: 'string', label: 'Secondary Text', group: 'basic' },
      { name: 'dense', type: 'boolean', label: 'Dense', group: 'basic' },
      { name: 'disablePadding', type: 'boolean', label: 'Disable Padding', group: 'basic' },
      { name: 'divider', type: 'boolean', label: 'Divider', group: 'basic' },
      { name: 'button', type: 'boolean', label: 'Clickable', group: 'basic' },
      { name: 'selected', type: 'boolean', label: 'Selected', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
    acceptsChildren: ['Checkbox', 'Switch', 'IconButton', 'Avatar', 'Badge'],
  },

  // Navigation Components
  {
    type: 'AppBar',
    label: 'App Bar',
    category: 'navigation',
    description: 'Top application bar',
    defaultProps: {
      position: 'static',
      color: 'primary',
    },
    availableProps: [
      { name: 'position', type: 'select', label: 'Position', options: ['fixed', 'absolute', 'sticky', 'static', 'relative'], group: 'basic' },
      { name: 'color', type: 'select', label: 'Color', options: ['default', 'inherit', 'primary', 'secondary', 'transparent'], group: 'basic' },
      { name: 'elevation', type: 'slider', label: 'Elevation', min: 0, max: 24, step: 1, group: 'style' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
  },
  {
    type: 'Tabs',
    label: 'Tabs',
    category: 'navigation',
    description: 'Tab navigation',
    defaultProps: {
      value: 0,
    },
    availableProps: [
      { name: 'value', type: 'number', label: 'Active Tab', group: 'basic' },
      { name: 'centered', type: 'boolean', label: 'Centered', group: 'basic' },
      { name: 'variant', type: 'select', label: 'Variant', options: ['standard', 'scrollable', 'fullWidth'], group: 'basic' },
      { name: 'indicatorColor', type: 'select', label: 'Indicator Color', options: ['primary', 'secondary'], group: 'basic' },
      { name: 'textColor', type: 'select', label: 'Text Color', options: ['inherit', 'primary', 'secondary'], group: 'basic' },
      { name: 'orientation', type: 'select', label: 'Orientation', options: ['horizontal', 'vertical'], group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
    acceptsChildren: ['Tab'],
  },
  {
    type: 'Tab',
    label: 'Tab',
    category: 'navigation',
    description: 'Single tab item',
    defaultProps: {
      label: 'Tab',
    },
    availableProps: [
      { name: 'label', type: 'string', label: 'Label', group: 'basic' },
      { name: 'disabled', type: 'boolean', label: 'Disabled', group: 'basic' },
      { name: 'wrapped', type: 'boolean', label: 'Wrapped', group: 'basic' },
      { name: 'icon', type: 'icon', label: 'Icon', group: 'basic' },
      { name: 'iconPosition', type: 'select', label: 'Icon Position', options: ['start', 'end', 'top', 'bottom'], group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },
  {
    type: 'Drawer',
    label: 'Drawer',
    category: 'navigation',
    description: 'Side navigation drawer',
    defaultProps: {
      anchor: 'left',
      variant: 'permanent',
      customStyles: { width: '240px' },
    },
    availableProps: [
      { name: 'anchor', type: 'select', label: 'Anchor', options: ['left', 'right', 'top', 'bottom'], group: 'basic' },
      { name: 'variant', type: 'select', label: 'Variant', options: ['permanent', 'persistent', 'temporary'], group: 'basic' },
      { name: 'open', type: 'boolean', label: 'Open', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
  },
  {
    type: 'Link',
    label: 'Link',
    category: 'navigation',
    description: 'Hyperlink element',
    defaultProps: {
      children: 'Link',
      href: '#',
    },
    availableProps: [
      { name: 'children', type: 'string', label: 'Text', group: 'basic' },
      { name: 'href', type: 'string', label: 'URL', group: 'basic' },
      { name: 'color', type: 'select', label: 'Color', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success', 'inherit'], group: 'basic' },
      { name: 'underline', type: 'select', label: 'Underline', options: ['always', 'hover', 'none'], group: 'basic' },
      { name: 'variant', type: 'select', label: 'Variant', options: ['body1', 'body2', 'button', 'caption', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'subtitle1', 'subtitle2'], group: 'basic' },
      { name: 'target', type: 'select', label: 'Target', options: ['_self', '_blank', '_parent', '_top'], group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },
  {
    type: 'Breadcrumbs',
    label: 'Breadcrumbs',
    category: 'navigation',
    description: 'Navigation breadcrumbs',
    defaultProps: {},
    availableProps: [
      { name: 'separator', type: 'string', label: 'Separator', group: 'basic' },
      { name: 'maxItems', type: 'number', label: 'Max Items', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
    acceptsChildren: ['Link', 'Typography'],
  },
  {
    type: 'IconButton',
    label: 'Icon Button',
    category: 'navigation',
    description: 'Clickable icon button',
    defaultProps: {
      color: 'default',
    },
    availableProps: [
      { name: 'color', type: 'select', label: 'Color', options: ['default', 'inherit', 'primary', 'secondary', 'error', 'warning', 'info', 'success'], group: 'basic' },
      { name: 'size', type: 'select', label: 'Size', options: ['small', 'medium', 'large'], group: 'basic' },
      { name: 'disabled', type: 'boolean', label: 'Disabled', group: 'basic' },
      { name: 'edge', type: 'select', label: 'Edge', options: ['start', 'end', 'false'], group: 'basic' },
      { name: 'icon', type: 'icon', label: 'Icon', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: false,
  },

  // Feedback Components
  {
    type: 'Dialog',
    label: 'Dialog',
    category: 'feedback',
    description: 'Modal dialog',
    defaultProps: {
      open: true,
      title: 'Dialog Title',
    },
    availableProps: [
      { name: 'open', type: 'boolean', label: 'Open', group: 'basic' },
      { name: 'title', type: 'string', label: 'Title', group: 'basic' },
      { name: 'fullWidth', type: 'boolean', label: 'Full Width', group: 'basic' },
      { name: 'maxWidth', type: 'select', label: 'Max Width', options: ['xs', 'sm', 'md', 'lg', 'xl', 'false'], group: 'basic' },
      { name: 'fullScreen', type: 'boolean', label: 'Full Screen', group: 'basic' },
      { name: 'scroll', type: 'select', label: 'Scroll', options: ['paper', 'body'], group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
  },
  {
    type: 'Tooltip',
    label: 'Tooltip',
    category: 'feedback',
    description: 'Tooltip on hover',
    defaultProps: {
      title: 'Tooltip text',
      placement: 'top',
    },
    availableProps: [
      { name: 'title', type: 'string', label: 'Tooltip Text', group: 'basic' },
      { name: 'placement', type: 'select', label: 'Placement', options: ['top', 'top-start', 'top-end', 'right', 'right-start', 'right-end', 'bottom', 'bottom-start', 'bottom-end', 'left', 'left-start', 'left-end'], group: 'basic' },
      { name: 'arrow', type: 'boolean', label: 'Show Arrow', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
  },

  // Accordion Components
  {
    type: 'Accordion',
    label: 'Accordion',
    category: 'surfaces',
    description: 'Expandable accordion panel',
    defaultProps: {
      defaultExpanded: false,
    },
    availableProps: [
      { name: 'defaultExpanded', type: 'boolean', label: 'Default Expanded', group: 'basic' },
      { name: 'disabled', type: 'boolean', label: 'Disabled', group: 'basic' },
      { name: 'disableGutters', type: 'boolean', label: 'Disable Gutters', group: 'basic' },
      { name: 'square', type: 'boolean', label: 'Square', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
    acceptsChildren: ['AccordionSummary', 'AccordionDetails'],
  },
  {
    type: 'AccordionSummary',
    label: 'Accordion Summary',
    category: 'surfaces',
    description: 'Accordion header',
    defaultProps: {
      children: 'Accordion Header',
    },
    availableProps: [
      { name: 'children', type: 'string', label: 'Text', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
  },
  {
    type: 'AccordionDetails',
    label: 'Accordion Details',
    category: 'surfaces',
    description: 'Accordion content',
    defaultProps: {
      children: 'Accordion content goes here',
    },
    availableProps: [
      { name: 'children', type: 'string', label: 'Text', group: 'basic' },
      ...commonStyleProps,
      ...commonSpacingProps,
      ...commonAdvancedProps,
    ],
    canHaveChildren: true,
  },
];

export const getComponentDefinition = (type: string): ComponentDefinition | undefined => {
  return componentDefinitions.find(def => def.type === type);
};

export const getComponentsByCategory = (category: string): ComponentDefinition[] => {
  return componentDefinitions.filter(def => def.category === category);
};

export const getAllCategories = (): string[] => {
  const categories = new Set(componentDefinitions.map(def => def.category));
  return Array.from(categories);
};
