import { useState, useMemo } from 'react';
import {
  Box,
  Paper,
  Typography,
  TextField,
  Button,
  IconButton,
  Tooltip,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Switch,
  FormControlLabel,
  Snackbar,
  Chip,
  Tabs,
  Tab,
} from '@mui/material';
import {
  ContentCopy,
  Home,
  Add,
  Delete,
  Download,
} from '@mui/icons-material';
import { Link } from 'react-router-dom';

interface Appender {
  id: string;
  name: string;
  type: 'console' | 'file' | 'rollingFile';
  pattern: string;
  // File appender specific
  file?: string;
  // Rolling file specific
  maxFileSize?: string;
  maxHistory?: number;
  totalSizeCap?: string;
}

interface Logger {
  id: string;
  name: string;
  level: string;
  additivity: boolean;
  appenderRefs: string[];
}

interface LoggingConfig {
  rootLevel: string;
  rootAppenders: string[];
  appenders: Appender[];
  loggers: Logger[];
  springProfile?: string;
}

const LOG_LEVELS = ['TRACE', 'DEBUG', 'INFO', 'WARN', 'ERROR', 'OFF'];

const PATTERN_PRESETS = {
  simple: '%d{HH:mm:ss} %-5level %logger{36} - %msg%n',
  detailed: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n',
  json: '{"timestamp":"%d{yyyy-MM-dd\'T\'HH:mm:ss.SSSZ}","level":"%level","logger":"%logger","message":"%msg","thread":"%thread"}%n',
  spring: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n',
};

export default function LogbackBuilder() {
  const [outputFormat, setOutputFormat] = useState<'logback' | 'log4j2-xml' | 'log4j2-yaml'>('logback');
  const [config, setConfig] = useState<LoggingConfig>({
    rootLevel: 'INFO',
    rootAppenders: ['CONSOLE'],
    appenders: [
      {
        id: '1',
        name: 'CONSOLE',
        type: 'console',
        pattern: PATTERN_PRESETS.detailed,
      },
      {
        id: '2',
        name: 'FILE',
        type: 'rollingFile',
        pattern: PATTERN_PRESETS.detailed,
        file: 'logs/application.log',
        maxFileSize: '10MB',
        maxHistory: 30,
        totalSizeCap: '1GB',
      },
    ],
    loggers: [
      { id: '1', name: 'com.example', level: 'DEBUG', additivity: true, appenderRefs: [] },
      { id: '2', name: 'org.springframework', level: 'INFO', additivity: true, appenderRefs: [] },
      { id: '3', name: 'org.hibernate.SQL', level: 'DEBUG', additivity: false, appenderRefs: ['CONSOLE'] },
    ],
  });
  const [snackbar, setSnackbar] = useState({ open: false, message: '' });

  const generatedConfig = useMemo(() => {
    if (outputFormat === 'logback') {
      let xml = `<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <!-- Generated by Logback Config Builder -->

`;

      // Appenders
      config.appenders.forEach(appender => {
        if (appender.type === 'console') {
          xml += `    <appender name="${appender.name}" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>${appender.pattern}</pattern>
        </encoder>
    </appender>

`;
        } else if (appender.type === 'file') {
          xml += `    <appender name="${appender.name}" class="ch.qos.logback.core.FileAppender">
        <file>${appender.file}</file>
        <encoder>
            <pattern>${appender.pattern}</pattern>
        </encoder>
    </appender>

`;
        } else if (appender.type === 'rollingFile') {
          xml += `    <appender name="${appender.name}" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${appender.file}</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
            <fileNamePattern>${appender.file}.%d{yyyy-MM-dd}.%i.gz</fileNamePattern>
            <maxFileSize>${appender.maxFileSize || '10MB'}</maxFileSize>
            <maxHistory>${appender.maxHistory || 30}</maxHistory>
            <totalSizeCap>${appender.totalSizeCap || '1GB'}</totalSizeCap>
        </rollingPolicy>
        <encoder>
            <pattern>${appender.pattern}</pattern>
        </encoder>
    </appender>

`;
        }
      });

      // Loggers
      config.loggers.forEach(logger => {
        xml += `    <logger name="${logger.name}" level="${logger.level}" additivity="${logger.additivity}"`;
        if (logger.appenderRefs.length === 0) {
          xml += '/>\n';
        } else {
          xml += '>\n';
          logger.appenderRefs.forEach(ref => {
            xml += `        <appender-ref ref="${ref}"/>\n`;
          });
          xml += '    </logger>\n';
        }
      });

      // Root logger
      xml += `
    <root level="${config.rootLevel}">
`;
      config.rootAppenders.forEach(ref => {
        xml += `        <appender-ref ref="${ref}"/>\n`;
      });
      xml += `    </root>
</configuration>`;

      return xml;
    }

    if (outputFormat === 'log4j2-xml') {
      let xml = `<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
    <!-- Generated by Log4j2 Config Builder -->

    <Appenders>
`;

      config.appenders.forEach(appender => {
        if (appender.type === 'console') {
          xml += `        <Console name="${appender.name}" target="SYSTEM_OUT">
            <PatternLayout pattern="${appender.pattern.replace(/%n/g, '%n')}"/>
        </Console>
`;
        } else if (appender.type === 'rollingFile') {
          xml += `        <RollingFile name="${appender.name}" fileName="${appender.file}"
                     filePattern="${appender.file}.%d{yyyy-MM-dd}.%i.gz">
            <PatternLayout pattern="${appender.pattern}"/>
            <Policies>
                <SizeBasedTriggeringPolicy size="${appender.maxFileSize || '10MB'}"/>
                <TimeBasedTriggeringPolicy/>
            </Policies>
            <DefaultRolloverStrategy max="${appender.maxHistory || 30}"/>
        </RollingFile>
`;
        }
      });

      xml += `    </Appenders>

    <Loggers>
`;

      config.loggers.forEach(logger => {
        xml += `        <Logger name="${logger.name}" level="${logger.level}" additivity="${logger.additivity}"`;
        if (logger.appenderRefs.length > 0) {
          xml += '>\n';
          logger.appenderRefs.forEach(ref => {
            xml += `            <AppenderRef ref="${ref}"/>\n`;
          });
          xml += '        </Logger>\n';
        } else {
          xml += '/>\n';
        }
      });

      xml += `        <Root level="${config.rootLevel}">
`;
      config.rootAppenders.forEach(ref => {
        xml += `            <AppenderRef ref="${ref}"/>\n`;
      });
      xml += `        </Root>
    </Loggers>
</Configuration>`;

      return xml;
    }

    if (outputFormat === 'log4j2-yaml') {
      let yaml = `# Generated by Log4j2 Config Builder
Configuration:
  status: warn

  Appenders:
`;

      config.appenders.forEach(appender => {
        if (appender.type === 'console') {
          yaml += `    Console:
      name: ${appender.name}
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "${appender.pattern}"
`;
        } else if (appender.type === 'rollingFile') {
          yaml += `    RollingFile:
      name: ${appender.name}
      fileName: ${appender.file}
      filePattern: "${appender.file}.%d{yyyy-MM-dd}.%i.gz"
      PatternLayout:
        pattern: "${appender.pattern}"
      Policies:
        SizeBasedTriggeringPolicy:
          size: ${appender.maxFileSize || '10MB'}
        TimeBasedTriggeringPolicy: {}
      DefaultRolloverStrategy:
        max: ${appender.maxHistory || 30}
`;
        }
      });

      yaml += `
  Loggers:
`;

      config.loggers.forEach(logger => {
        yaml += `    Logger:
      name: ${logger.name}
      level: ${logger.level}
      additivity: ${logger.additivity}
`;
        if (logger.appenderRefs.length > 0) {
          yaml += '      AppenderRef:\n';
          logger.appenderRefs.forEach(ref => {
            yaml += `        - ref: ${ref}\n`;
          });
        }
      });

      yaml += `    Root:
      level: ${config.rootLevel}
      AppenderRef:
`;
      config.rootAppenders.forEach(ref => {
        yaml += `        - ref: ${ref}\n`;
      });

      return yaml;
    }

    return '';
  }, [config, outputFormat]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generatedConfig);
    setSnackbar({ open: true, message: 'Copied to clipboard' });
  };

  const handleDownload = () => {
    const filenames: Record<string, string> = {
      'logback': 'logback.xml',
      'log4j2-xml': 'log4j2.xml',
      'log4j2-yaml': 'log4j2.yaml',
    };
    const blob = new Blob([generatedConfig], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filenames[outputFormat];
    a.click();
    URL.revokeObjectURL(url);
  };

  const addAppender = () => {
    setConfig({
      ...config,
      appenders: [...config.appenders, {
        id: String(Date.now()),
        name: 'NEW_APPENDER',
        type: 'console',
        pattern: PATTERN_PRESETS.simple,
      }],
    });
  };

  const removeAppender = (id: string) => {
    setConfig({ ...config, appenders: config.appenders.filter(a => a.id !== id) });
  };

  const updateAppender = (id: string, updates: Partial<Appender>) => {
    setConfig({
      ...config,
      appenders: config.appenders.map(a => a.id === id ? { ...a, ...updates } : a),
    });
  };

  const addLogger = () => {
    setConfig({
      ...config,
      loggers: [...config.loggers, {
        id: String(Date.now()),
        name: 'com.example.new',
        level: 'DEBUG',
        additivity: true,
        appenderRefs: [],
      }],
    });
  };

  const removeLogger = (id: string) => {
    setConfig({ ...config, loggers: config.loggers.filter(l => l.id !== id) });
  };

  const updateLogger = (id: string, updates: Partial<Logger>) => {
    setConfig({
      ...config,
      loggers: config.loggers.map(l => l.id === id ? { ...l, ...updates } : l),
    });
  };

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: '#0a0a0a' }}>
      <Paper elevation={0} sx={{ bgcolor: '#111', borderBottom: '1px solid #222', px: 3, py: 2 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
            <Link to="/"><IconButton size="small" sx={{ color: 'grey.500' }}><Home /></IconButton></Link>
            <Typography variant="h5" sx={{ color: 'white', fontWeight: 600 }}>Logback/Log4j2 Config Builder</Typography>
            <Chip label="Java Logging" size="small" color="warning" />
          </Box>
          <Box sx={{ display: 'flex', gap: 1 }}>
            <Tooltip title="Download"><IconButton onClick={handleDownload} sx={{ color: 'grey.500' }}><Download /></IconButton></Tooltip>
            <Tooltip title="Copy"><IconButton onClick={handleCopy} sx={{ color: 'grey.500' }}><ContentCopy /></IconButton></Tooltip>
          </Box>
        </Box>
      </Paper>

      <Box sx={{ display: 'flex', height: 'calc(100vh - 70px)' }}>
        {/* Builder Panel */}
        <Box sx={{ flex: 1, p: 2, overflow: 'auto' }}>
          <Tabs value={outputFormat} onChange={(_, v) => setOutputFormat(v)} sx={{ mb: 2 }}>
            <Tab value="logback" label="Logback (XML)" sx={{ color: 'grey.400' }} />
            <Tab value="log4j2-xml" label="Log4j2 (XML)" sx={{ color: 'grey.400' }} />
            <Tab value="log4j2-yaml" label="Log4j2 (YAML)" sx={{ color: 'grey.400' }} />
          </Tabs>

          {/* Root Logger */}
          <Paper sx={{ bgcolor: '#111', border: '1px solid #222', p: 2, mb: 2 }}>
            <Typography variant="subtitle1" sx={{ color: 'grey.300', mb: 2 }}>Root Logger</Typography>
            <Box sx={{ display: 'flex', gap: 2, alignItems: 'center' }}>
              <FormControl size="small" sx={{ minWidth: 120 }}>
                <InputLabel sx={{ color: 'grey.500' }}>Level</InputLabel>
                <Select value={config.rootLevel} label="Level" onChange={(e) => setConfig({ ...config, rootLevel: e.target.value })} sx={{ color: 'grey.300' }}>
                  {LOG_LEVELS.map(l => <MenuItem key={l} value={l}>{l}</MenuItem>)}
                </Select>
              </FormControl>
              <Box sx={{ display: 'flex', gap: 0.5, flexWrap: 'wrap' }}>
                {config.appenders.map(a => (
                  <Chip
                    key={a.id}
                    label={a.name}
                    size="small"
                    color={config.rootAppenders.includes(a.name) ? 'primary' : 'default'}
                    onClick={() => {
                      const newRefs = config.rootAppenders.includes(a.name)
                        ? config.rootAppenders.filter(r => r !== a.name)
                        : [...config.rootAppenders, a.name];
                      setConfig({ ...config, rootAppenders: newRefs });
                    }}
                    sx={{ cursor: 'pointer' }}
                  />
                ))}
              </Box>
            </Box>
          </Paper>

          {/* Appenders */}
          <Paper sx={{ bgcolor: '#111', border: '1px solid #222', p: 2, mb: 2 }}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
              <Typography variant="subtitle1" sx={{ color: 'grey.300' }}>Appenders</Typography>
              <Button startIcon={<Add />} onClick={addAppender} size="small" sx={{ color: 'grey.400' }}>Add Appender</Button>
            </Box>

            {config.appenders.map(appender => (
              <Paper key={appender.id} sx={{ bgcolor: '#0a0a0a', border: '1px solid #333', p: 2, mb: 2 }}>
                <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
                  <TextField size="small" label="Name" value={appender.name} onChange={(e) => updateAppender(appender.id, { name: e.target.value })} sx={{ width: 150, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                  <FormControl size="small" sx={{ minWidth: 130 }}>
                    <InputLabel sx={{ color: 'grey.500' }}>Type</InputLabel>
                    <Select value={appender.type} label="Type" onChange={(e) => updateAppender(appender.id, { type: e.target.value as Appender['type'] })} sx={{ color: 'grey.300' }}>
                      <MenuItem value="console">Console</MenuItem>
                      <MenuItem value="file">File</MenuItem>
                      <MenuItem value="rollingFile">Rolling File</MenuItem>
                    </Select>
                  </FormControl>
                  <IconButton size="small" onClick={() => removeAppender(appender.id)} sx={{ color: 'grey.500' }}><Delete /></IconButton>
                </Box>

                {(appender.type === 'file' || appender.type === 'rollingFile') && (
                  <TextField size="small" label="File Path" value={appender.file || ''} onChange={(e) => updateAppender(appender.id, { file: e.target.value })} fullWidth sx={{ mb: 2, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                )}

                {appender.type === 'rollingFile' && (
                  <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
                    <TextField size="small" label="Max File Size" value={appender.maxFileSize || ''} onChange={(e) => updateAppender(appender.id, { maxFileSize: e.target.value })} placeholder="10MB" sx={{ flex: 1, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                    <TextField size="small" label="Max History (days)" type="number" value={appender.maxHistory || ''} onChange={(e) => updateAppender(appender.id, { maxHistory: parseInt(e.target.value) || undefined })} sx={{ flex: 1, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                    <TextField size="small" label="Total Size Cap" value={appender.totalSizeCap || ''} onChange={(e) => updateAppender(appender.id, { totalSizeCap: e.target.value })} placeholder="1GB" sx={{ flex: 1, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                  </Box>
                )}

                <Typography variant="caption" sx={{ color: 'grey.500', display: 'block', mb: 1 }}>Pattern Presets</Typography>
                <Box sx={{ display: 'flex', gap: 0.5, flexWrap: 'wrap', mb: 1 }}>
                  {Object.entries(PATTERN_PRESETS).map(([name, pattern]) => (
                    <Chip
                      key={name}
                      label={name}
                      size="small"
                      onClick={() => updateAppender(appender.id, { pattern })}
                      color={appender.pattern === pattern ? 'primary' : 'default'}
                      sx={{ cursor: 'pointer', fontSize: 10 }}
                    />
                  ))}
                </Box>
                <TextField size="small" label="Pattern" value={appender.pattern} onChange={(e) => updateAppender(appender.id, { pattern: e.target.value })} fullWidth multiline rows={2} sx={{ '& .MuiInputBase-root': { color: 'grey.300', fontFamily: 'monospace', fontSize: 11 } }} />
              </Paper>
            ))}
          </Paper>

          {/* Loggers */}
          <Paper sx={{ bgcolor: '#111', border: '1px solid #222', p: 2 }}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
              <Typography variant="subtitle1" sx={{ color: 'grey.300' }}>Loggers</Typography>
              <Button startIcon={<Add />} onClick={addLogger} size="small" sx={{ color: 'grey.400' }}>Add Logger</Button>
            </Box>

            {config.loggers.map(logger => (
              <Paper key={logger.id} sx={{ bgcolor: '#0a0a0a', border: '1px solid #333', p: 2, mb: 1 }}>
                <Box sx={{ display: 'flex', gap: 2, alignItems: 'center' }}>
                  <TextField size="small" label="Package/Class" value={logger.name} onChange={(e) => updateLogger(logger.id, { name: e.target.value })} sx={{ flex: 1, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                  <FormControl size="small" sx={{ minWidth: 100 }}>
                    <InputLabel sx={{ color: 'grey.500' }}>Level</InputLabel>
                    <Select value={logger.level} label="Level" onChange={(e) => updateLogger(logger.id, { level: e.target.value })} sx={{ color: 'grey.300' }}>
                      {LOG_LEVELS.map(l => <MenuItem key={l} value={l}>{l}</MenuItem>)}
                    </Select>
                  </FormControl>
                  <FormControlLabel
                    control={<Switch checked={logger.additivity} onChange={(e) => updateLogger(logger.id, { additivity: e.target.checked })} size="small" />}
                    label={<Typography sx={{ color: 'grey.400', fontSize: 12 }}>Additivity</Typography>}
                  />
                  <IconButton size="small" onClick={() => removeLogger(logger.id)} sx={{ color: 'grey.500' }}><Delete /></IconButton>
                </Box>
              </Paper>
            ))}
          </Paper>
        </Box>

        {/* Output Panel */}
        <Box sx={{ width: 550, borderLeft: '1px solid #222', display: 'flex', flexDirection: 'column' }}>
          <Box sx={{ p: 2, borderBottom: '1px solid #222' }}>
            <Typography variant="subtitle2" sx={{ color: 'grey.400' }}>
              {outputFormat === 'logback' ? 'logback.xml' : outputFormat === 'log4j2-xml' ? 'log4j2.xml' : 'log4j2.yaml'}
            </Typography>
          </Box>
          <Box sx={{ flex: 1, p: 2, overflow: 'auto' }}>
            <Paper sx={{ bgcolor: '#0a0a0a', p: 2, border: '1px solid #333', height: '100%' }}>
              <Typography component="pre" sx={{ fontFamily: 'monospace', fontSize: 11, color: '#d4d4d4', m: 0, whiteSpace: 'pre-wrap' }}>
                {generatedConfig}
              </Typography>
            </Paper>
          </Box>
        </Box>
      </Box>

      <Snackbar open={snackbar.open} autoHideDuration={2000} onClose={() => setSnackbar({ ...snackbar, open: false })} message={snackbar.message} />
    </Box>
  );
}
