import { useState, useMemo } from 'react';
import {
  Box,
  Paper,
  Typography,
  TextField,
  Button,
  IconButton,
  Tooltip,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Switch,
  FormControlLabel,
  Snackbar,
  Chip,
  Tabs,
  Tab,
} from '@mui/material';
import {
  ContentCopy,
  Home,
  Add,
  Delete,
  Download,
} from '@mui/icons-material';
import { Link } from 'react-router-dom';

interface Column {
  id: string;
  name: string;
  type: string;
  nullable: boolean;
  primaryKey: boolean;
  autoIncrement: boolean;
  unique: boolean;
  defaultValue?: string;
  foreignKey?: {
    table: string;
    column: string;
    onDelete?: string;
    onUpdate?: string;
  };
}

interface Index {
  id: string;
  name: string;
  columns: string[];
  unique: boolean;
}

interface TableConfig {
  name: string;
  columns: Column[];
  indexes: Index[];
}

type MigrationType = 'flyway' | 'liquibase-xml' | 'liquibase-yaml' | 'raw-sql';

const SQL_TYPES: Record<string, string[]> = {
  postgresql: ['BIGINT', 'INTEGER', 'SMALLINT', 'SERIAL', 'BIGSERIAL', 'VARCHAR', 'TEXT', 'BOOLEAN', 'TIMESTAMP', 'TIMESTAMPTZ', 'DATE', 'TIME', 'UUID', 'JSONB', 'JSON', 'BYTEA', 'NUMERIC', 'DECIMAL', 'REAL', 'DOUBLE PRECISION'],
  mysql: ['BIGINT', 'INT', 'SMALLINT', 'TINYINT', 'VARCHAR', 'TEXT', 'LONGTEXT', 'BOOLEAN', 'DATETIME', 'TIMESTAMP', 'DATE', 'TIME', 'CHAR', 'BLOB', 'JSON', 'DECIMAL', 'FLOAT', 'DOUBLE'],
};

export default function MigrationGenerator() {
  const [migrationType, setMigrationType] = useState<MigrationType>('flyway');
  const [database, setDatabase] = useState<'postgresql' | 'mysql'>('postgresql');
  const [version, setVersion] = useState('V1__');
  const [description, setDescription] = useState('create_users_table');
  const [table, setTable] = useState<TableConfig>({
    name: 'users',
    columns: [
      { id: '1', name: 'id', type: 'BIGSERIAL', nullable: false, primaryKey: true, autoIncrement: true, unique: false },
      { id: '2', name: 'username', type: 'VARCHAR(50)', nullable: false, primaryKey: false, autoIncrement: false, unique: true },
      { id: '3', name: 'email', type: 'VARCHAR(100)', nullable: false, primaryKey: false, autoIncrement: false, unique: true },
      { id: '4', name: 'password_hash', type: 'VARCHAR(255)', nullable: false, primaryKey: false, autoIncrement: false, unique: false },
      { id: '5', name: 'active', type: 'BOOLEAN', nullable: false, primaryKey: false, autoIncrement: false, unique: false, defaultValue: 'true' },
      { id: '6', name: 'created_at', type: 'TIMESTAMPTZ', nullable: false, primaryKey: false, autoIncrement: false, unique: false, defaultValue: 'CURRENT_TIMESTAMP' },
      { id: '7', name: 'updated_at', type: 'TIMESTAMPTZ', nullable: true, primaryKey: false, autoIncrement: false, unique: false },
    ],
    indexes: [
      { id: '1', name: 'idx_users_email', columns: ['email'], unique: false },
    ],
  });
  const [snackbar, setSnackbar] = useState({ open: false, message: '' });

  const generatedMigration = useMemo(() => {
    const pkColumns = table.columns.filter(c => c.primaryKey);

    if (migrationType === 'flyway' || migrationType === 'raw-sql') {
      let sql = `-- Migration: ${description}\n-- Generated by Migration Generator\n\n`;

      sql += `CREATE TABLE ${table.name} (\n`;

      const columnDefs = table.columns.map(col => {
        let def = `    ${col.name} ${col.type}`;
        if (!col.nullable) def += ' NOT NULL';
        if (col.unique && !col.primaryKey) def += ' UNIQUE';
        if (col.defaultValue) def += ` DEFAULT ${col.defaultValue}`;
        return def;
      });

      if (pkColumns.length > 0) {
        columnDefs.push(`    PRIMARY KEY (${pkColumns.map(c => c.name).join(', ')})`);
      }

      // Foreign keys
      table.columns.filter(c => c.foreignKey).forEach(col => {
        let fk = `    FOREIGN KEY (${col.name}) REFERENCES ${col.foreignKey!.table}(${col.foreignKey!.column})`;
        if (col.foreignKey!.onDelete) fk += ` ON DELETE ${col.foreignKey!.onDelete}`;
        if (col.foreignKey!.onUpdate) fk += ` ON UPDATE ${col.foreignKey!.onUpdate}`;
        columnDefs.push(fk);
      });

      sql += columnDefs.join(',\n');
      sql += '\n);\n\n';

      // Indexes
      table.indexes.forEach(idx => {
        sql += `CREATE ${idx.unique ? 'UNIQUE ' : ''}INDEX ${idx.name} ON ${table.name} (${idx.columns.join(', ')});\n`;
      });

      return sql;
    }

    if (migrationType === 'liquibase-xml') {
      let xml = `<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                        http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">

    <changeSet id="${version.replace('V', '').replace('__', '')}" author="developer">
        <createTable tableName="${table.name}">
`;

      table.columns.forEach(col => {
        const typeMap: Record<string, string> = {
          'BIGSERIAL': 'BIGINT', 'SERIAL': 'INT', 'TIMESTAMPTZ': 'TIMESTAMP WITH TIME ZONE',
          'BOOLEAN': 'BOOLEAN', 'TEXT': 'CLOB', 'JSONB': 'CLOB', 'BYTEA': 'BLOB',
        };
        const lbType = typeMap[col.type] || col.type;

        xml += `            <column name="${col.name}" type="${lbType}"`;
        if (col.autoIncrement) xml += ' autoIncrement="true"';
        xml += '>\n';

        if (!col.nullable || col.primaryKey) {
          xml += '                <constraints';
          if (col.primaryKey) xml += ' primaryKey="true"';
          if (!col.nullable) xml += ' nullable="false"';
          if (col.unique && !col.primaryKey) xml += ' unique="true"';
          xml += '/>\n';
        }

        if (col.defaultValue) {
          xml += `                <defaultValue>${col.defaultValue}</defaultValue>\n`;
        }

        xml += '            </column>\n';
      });

      xml += `        </createTable>\n`;

      // Indexes
      table.indexes.forEach(idx => {
        xml += `        <createIndex indexName="${idx.name}" tableName="${table.name}"${idx.unique ? ' unique="true"' : ''}>\n`;
        idx.columns.forEach(colName => {
          xml += `            <column name="${colName}"/>\n`;
        });
        xml += '        </createIndex>\n';
      });

      xml += `    </changeSet>
</databaseChangeLog>`;

      return xml;
    }

    if (migrationType === 'liquibase-yaml') {
      let yaml = `databaseChangeLog:
  - changeSet:
      id: ${version.replace('V', '').replace('__', '')}
      author: developer
      changes:
        - createTable:
            tableName: ${table.name}
            columns:
`;

      table.columns.forEach(col => {
        yaml += `              - column:
                  name: ${col.name}
                  type: ${col.type}
`;
        if (col.autoIncrement) yaml += '                  autoIncrement: true\n';

        const constraints: string[] = [];
        if (col.primaryKey) constraints.push('primaryKey: true');
        if (!col.nullable) constraints.push('nullable: false');
        if (col.unique && !col.primaryKey) constraints.push('unique: true');

        if (constraints.length > 0) {
          yaml += '                  constraints:\n';
          constraints.forEach(c => yaml += `                    ${c}\n`);
        }

        if (col.defaultValue) {
          yaml += `                  defaultValue: "${col.defaultValue}"\n`;
        }
      });

      // Indexes
      table.indexes.forEach(idx => {
        yaml += `        - createIndex:
            indexName: ${idx.name}
            tableName: ${table.name}
`;
        if (idx.unique) yaml += '            unique: true\n';
        yaml += '            columns:\n';
        idx.columns.forEach(colName => {
          yaml += `              - column:\n                  name: ${colName}\n`;
        });
      });

      return yaml;
    }

    return '';
  }, [table, migrationType, version, description]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generatedMigration);
    setSnackbar({ open: true, message: 'Copied to clipboard' });
  };

  const handleDownload = () => {
    const extensions: Record<MigrationType, string> = {
      'flyway': 'sql',
      'raw-sql': 'sql',
      'liquibase-xml': 'xml',
      'liquibase-yaml': 'yaml',
    };
    const filename = migrationType === 'flyway'
      ? `${version}${description}.sql`
      : `${description}.${extensions[migrationType]}`;

    const blob = new Blob([generatedMigration], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const addColumn = () => {
    setTable({
      ...table,
      columns: [...table.columns, {
        id: String(Date.now()),
        name: 'new_column',
        type: 'VARCHAR(255)',
        nullable: true,
        primaryKey: false,
        autoIncrement: false,
        unique: false,
      }],
    });
  };

  const removeColumn = (id: string) => {
    setTable({ ...table, columns: table.columns.filter(c => c.id !== id) });
  };

  const updateColumn = (id: string, updates: Partial<Column>) => {
    setTable({
      ...table,
      columns: table.columns.map(c => c.id === id ? { ...c, ...updates } : c),
    });
  };

  const addIndex = () => {
    setTable({
      ...table,
      indexes: [...table.indexes, {
        id: String(Date.now()),
        name: `idx_${table.name}_new`,
        columns: [],
        unique: false,
      }],
    });
  };

  const removeIndex = (id: string) => {
    setTable({ ...table, indexes: table.indexes.filter(i => i.id !== id) });
  };

  const updateIndex = (id: string, updates: Partial<Index>) => {
    setTable({
      ...table,
      indexes: table.indexes.map(i => i.id === id ? { ...i, ...updates } : i),
    });
  };

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: '#0a0a0a' }}>
      <Paper elevation={0} sx={{ bgcolor: '#111', borderBottom: '1px solid #222', px: 3, py: 2 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
            <Link to="/"><IconButton size="small" sx={{ color: 'grey.500' }}><Home /></IconButton></Link>
            <Typography variant="h5" sx={{ color: 'white', fontWeight: 600 }}>Database Migration Generator</Typography>
            <Chip label="Flyway/Liquibase" size="small" color="info" />
          </Box>
          <Box sx={{ display: 'flex', gap: 1 }}>
            <Tooltip title="Download"><IconButton onClick={handleDownload} sx={{ color: 'grey.500' }}><Download /></IconButton></Tooltip>
            <Tooltip title="Copy"><IconButton onClick={handleCopy} sx={{ color: 'grey.500' }}><ContentCopy /></IconButton></Tooltip>
          </Box>
        </Box>
      </Paper>

      <Box sx={{ display: 'flex', height: 'calc(100vh - 70px)' }}>
        {/* Builder Panel */}
        <Box sx={{ flex: 1, p: 2, overflow: 'auto' }}>
          {/* Migration Settings */}
          <Paper sx={{ bgcolor: '#111', border: '1px solid #222', p: 2, mb: 2 }}>
            <Typography variant="subtitle1" sx={{ color: 'grey.300', mb: 2 }}>Migration Settings</Typography>
            <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
              <Tabs value={migrationType} onChange={(_, v) => setMigrationType(v)} sx={{ minHeight: 36 }}>
                <Tab value="flyway" label="Flyway" sx={{ color: 'grey.400', fontSize: 12, minHeight: 36 }} />
                <Tab value="liquibase-xml" label="Liquibase XML" sx={{ color: 'grey.400', fontSize: 12, minHeight: 36 }} />
                <Tab value="liquibase-yaml" label="Liquibase YAML" sx={{ color: 'grey.400', fontSize: 12, minHeight: 36 }} />
                <Tab value="raw-sql" label="Raw SQL" sx={{ color: 'grey.400', fontSize: 12, minHeight: 36 }} />
              </Tabs>
            </Box>
            <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
              <FormControl size="small" sx={{ minWidth: 130 }}>
                <InputLabel sx={{ color: 'grey.500' }}>Database</InputLabel>
                <Select value={database} label="Database" onChange={(e) => setDatabase(e.target.value as 'postgresql' | 'mysql')} sx={{ color: 'grey.300' }}>
                  <MenuItem value="postgresql">PostgreSQL</MenuItem>
                  <MenuItem value="mysql">MySQL</MenuItem>
                </Select>
              </FormControl>
              <TextField size="small" label="Version" value={version} onChange={(e) => setVersion(e.target.value)} sx={{ width: 100, '& .MuiInputBase-root': { color: 'grey.300' } }} />
              <TextField size="small" label="Description" value={description} onChange={(e) => setDescription(e.target.value)} sx={{ flex: 1, '& .MuiInputBase-root': { color: 'grey.300' } }} />
            </Box>
            <TextField size="small" label="Table Name" value={table.name} onChange={(e) => setTable({ ...table, name: e.target.value })} sx={{ '& .MuiInputBase-root': { color: 'grey.300' } }} />
          </Paper>

          {/* Columns */}
          <Paper sx={{ bgcolor: '#111', border: '1px solid #222', p: 2, mb: 2 }}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
              <Typography variant="subtitle1" sx={{ color: 'grey.300' }}>Columns</Typography>
              <Button startIcon={<Add />} onClick={addColumn} size="small" sx={{ color: 'grey.400' }}>Add Column</Button>
            </Box>

            {table.columns.map(col => (
              <Paper key={col.id} sx={{ bgcolor: '#0a0a0a', border: '1px solid #333', p: 2, mb: 1 }}>
                <Box sx={{ display: 'flex', gap: 2, mb: 1 }}>
                  <TextField size="small" label="Name" value={col.name} onChange={(e) => updateColumn(col.id, { name: e.target.value })} sx={{ flex: 1, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                  <FormControl size="small" sx={{ minWidth: 160 }}>
                    <InputLabel sx={{ color: 'grey.500' }}>Type</InputLabel>
                    <Select value={col.type} label="Type" onChange={(e) => updateColumn(col.id, { type: e.target.value })} sx={{ color: 'grey.300' }}>
                      {SQL_TYPES[database].map(t => <MenuItem key={t} value={t}>{t}</MenuItem>)}
                      <MenuItem value="VARCHAR(50)">VARCHAR(50)</MenuItem>
                      <MenuItem value="VARCHAR(100)">VARCHAR(100)</MenuItem>
                      <MenuItem value="VARCHAR(255)">VARCHAR(255)</MenuItem>
                    </Select>
                  </FormControl>
                  <TextField size="small" label="Default" value={col.defaultValue || ''} onChange={(e) => updateColumn(col.id, { defaultValue: e.target.value || undefined })} placeholder="optional" sx={{ width: 150, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                  <IconButton size="small" onClick={() => removeColumn(col.id)} sx={{ color: 'grey.500' }}><Delete /></IconButton>
                </Box>
                <Box sx={{ display: 'flex', gap: 2, alignItems: 'center' }}>
                  <FormControlLabel control={<Switch checked={col.primaryKey} onChange={(e) => updateColumn(col.id, { primaryKey: e.target.checked })} size="small" />} label={<Typography sx={{ color: 'grey.400', fontSize: 12 }}>PK</Typography>} />
                  <FormControlLabel control={<Switch checked={!col.nullable} onChange={(e) => updateColumn(col.id, { nullable: !e.target.checked })} size="small" />} label={<Typography sx={{ color: 'grey.400', fontSize: 12 }}>NOT NULL</Typography>} />
                  <FormControlLabel control={<Switch checked={col.unique} onChange={(e) => updateColumn(col.id, { unique: e.target.checked })} size="small" />} label={<Typography sx={{ color: 'grey.400', fontSize: 12 }}>UNIQUE</Typography>} />
                  <FormControlLabel control={<Switch checked={col.autoIncrement} onChange={(e) => updateColumn(col.id, { autoIncrement: e.target.checked })} size="small" />} label={<Typography sx={{ color: 'grey.400', fontSize: 12 }}>AUTO_INC</Typography>} />
                </Box>
              </Paper>
            ))}
          </Paper>

          {/* Indexes */}
          <Paper sx={{ bgcolor: '#111', border: '1px solid #222', p: 2 }}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
              <Typography variant="subtitle1" sx={{ color: 'grey.300' }}>Indexes</Typography>
              <Button startIcon={<Add />} onClick={addIndex} size="small" sx={{ color: 'grey.400' }}>Add Index</Button>
            </Box>

            {table.indexes.map(idx => (
              <Paper key={idx.id} sx={{ bgcolor: '#0a0a0a', border: '1px solid #333', p: 2, mb: 1 }}>
                <Box sx={{ display: 'flex', gap: 2, mb: 1 }}>
                  <TextField size="small" label="Index Name" value={idx.name} onChange={(e) => updateIndex(idx.id, { name: e.target.value })} sx={{ flex: 1, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                  <FormControlLabel control={<Switch checked={idx.unique} onChange={(e) => updateIndex(idx.id, { unique: e.target.checked })} size="small" />} label={<Typography sx={{ color: 'grey.400', fontSize: 12 }}>Unique</Typography>} />
                  <IconButton size="small" onClick={() => removeIndex(idx.id)} sx={{ color: 'grey.500' }}><Delete /></IconButton>
                </Box>
                <Box sx={{ display: 'flex', gap: 0.5, flexWrap: 'wrap' }}>
                  {table.columns.map(col => (
                    <Chip
                      key={col.id}
                      label={col.name}
                      size="small"
                      color={idx.columns.includes(col.name) ? 'primary' : 'default'}
                      onClick={() => {
                        const newCols = idx.columns.includes(col.name)
                          ? idx.columns.filter(c => c !== col.name)
                          : [...idx.columns, col.name];
                        updateIndex(idx.id, { columns: newCols });
                      }}
                      sx={{ cursor: 'pointer' }}
                    />
                  ))}
                </Box>
              </Paper>
            ))}
          </Paper>
        </Box>

        {/* Output Panel */}
        <Box sx={{ width: 550, borderLeft: '1px solid #222', display: 'flex', flexDirection: 'column' }}>
          <Box sx={{ p: 2, borderBottom: '1px solid #222' }}>
            <Typography variant="subtitle2" sx={{ color: 'grey.400' }}>
              {migrationType === 'flyway' ? `${version}${description}.sql` :
               migrationType === 'liquibase-xml' ? 'changelog.xml' :
               migrationType === 'liquibase-yaml' ? 'changelog.yaml' : 'migration.sql'}
            </Typography>
          </Box>
          <Box sx={{ flex: 1, p: 2, overflow: 'auto' }}>
            <Paper sx={{ bgcolor: '#0a0a0a', p: 2, border: '1px solid #333', height: '100%' }}>
              <Typography component="pre" sx={{ fontFamily: 'monospace', fontSize: 11, color: '#d4d4d4', m: 0, whiteSpace: 'pre-wrap' }}>
                {generatedMigration}
              </Typography>
            </Paper>
          </Box>
        </Box>
      </Box>

      <Snackbar open={snackbar.open} autoHideDuration={2000} onClose={() => setSnackbar({ ...snackbar, open: false })} message={snackbar.message} />
    </Box>
  );
}
