import { useState, useMemo } from 'react';
import {
  Box,
  Paper,
  Typography,
  TextField,
  Button,
  IconButton,
  Tooltip,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Switch,
  FormControlLabel,
  Snackbar,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Chip,
  Tabs,
  Tab,
} from '@mui/material';
import {
  ContentCopy,
  Home,
  Add,
  Delete,
  ExpandMore,
  Download,
} from '@mui/icons-material';
import { Link } from 'react-router-dom';

interface DataSourceConfig {
  url: string;
  username: string;
  password: string;
  driverClassName: string;
  hikari: {
    maximumPoolSize: number;
    minimumIdle: number;
    connectionTimeout: number;
  };
}

interface JpaConfig {
  showSql: boolean;
  hibernate: {
    ddlAuto: string;
    dialect: string;
  };
}

interface ServerConfig {
  port: number;
  contextPath: string;
  ssl: {
    enabled: boolean;
    keyStore: string;
    keyStorePassword: string;
  };
}

interface LoggingConfig {
  level: {
    root: string;
    app: string;
    sql: string;
  };
  pattern: string;
}

interface SpringConfig {
  server: ServerConfig;
  datasource: DataSourceConfig;
  jpa: JpaConfig;
  logging: LoggingConfig;
  profiles: string[];
  customProperties: { key: string; value: string }[];
}

const DATABASE_PRESETS = {
  postgresql: {
    driverClassName: 'org.postgresql.Driver',
    urlTemplate: 'jdbc:postgresql://localhost:5432/mydb',
    dialect: 'org.hibernate.dialect.PostgreSQLDialect',
  },
  mysql: {
    driverClassName: 'com.mysql.cj.jdbc.Driver',
    urlTemplate: 'jdbc:mysql://localhost:3306/mydb',
    dialect: 'org.hibernate.dialect.MySQLDialect',
  },
  oracle: {
    driverClassName: 'oracle.jdbc.OracleDriver',
    urlTemplate: 'jdbc:oracle:thin:@localhost:1521:xe',
    dialect: 'org.hibernate.dialect.OracleDialect',
  },
  h2: {
    driverClassName: 'org.h2.Driver',
    urlTemplate: 'jdbc:h2:mem:testdb',
    dialect: 'org.hibernate.dialect.H2Dialect',
  },
  sqlserver: {
    driverClassName: 'com.microsoft.sqlserver.jdbc.SQLServerDriver',
    urlTemplate: 'jdbc:sqlserver://localhost:1433;databaseName=mydb',
    dialect: 'org.hibernate.dialect.SQLServerDialect',
  },
};

export default function SpringConfigBuilder() {
  const [format, setFormat] = useState<'yaml' | 'properties'>('yaml');
  const [config, setConfig] = useState<SpringConfig>({
    server: {
      port: 8080,
      contextPath: '/api',
      ssl: { enabled: false, keyStore: '', keyStorePassword: '' },
    },
    datasource: {
      url: 'jdbc:postgresql://localhost:5432/mydb',
      username: 'postgres',
      password: '',
      driverClassName: 'org.postgresql.Driver',
      hikari: { maximumPoolSize: 10, minimumIdle: 5, connectionTimeout: 30000 },
    },
    jpa: {
      showSql: true,
      hibernate: { ddlAuto: 'update', dialect: 'org.hibernate.dialect.PostgreSQLDialect' },
    },
    logging: {
      level: { root: 'INFO', app: 'DEBUG', sql: 'DEBUG' },
      pattern: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n',
    },
    profiles: ['dev'],
    customProperties: [],
  });
  const [snackbar, setSnackbar] = useState({ open: false, message: '' });

  const applyDatabasePreset = (preset: keyof typeof DATABASE_PRESETS) => {
    const p = DATABASE_PRESETS[preset];
    setConfig({
      ...config,
      datasource: { ...config.datasource, url: p.urlTemplate, driverClassName: p.driverClassName },
      jpa: { ...config.jpa, hibernate: { ...config.jpa.hibernate, dialect: p.dialect } },
    });
  };

  const generatedConfig = useMemo(() => {
    if (format === 'yaml') {
      let yaml = `# Spring Boot Application Configuration
# Generated by Spring Config Builder

spring:
  profiles:
    active: ${config.profiles.join(', ')}

  datasource:
    url: ${config.datasource.url}
    username: ${config.datasource.username}
    password: ${config.datasource.password || '${DB_PASSWORD}'}
    driver-class-name: ${config.datasource.driverClassName}
    hikari:
      maximum-pool-size: ${config.datasource.hikari.maximumPoolSize}
      minimum-idle: ${config.datasource.hikari.minimumIdle}
      connection-timeout: ${config.datasource.hikari.connectionTimeout}

  jpa:
    show-sql: ${config.jpa.showSql}
    hibernate:
      ddl-auto: ${config.jpa.hibernate.ddlAuto}
    properties:
      hibernate:
        dialect: ${config.jpa.hibernate.dialect}
        format_sql: true

server:
  port: ${config.server.port}
  servlet:
    context-path: ${config.server.contextPath}
`;

      if (config.server.ssl.enabled) {
        yaml += `  ssl:
    enabled: true
    key-store: ${config.server.ssl.keyStore}
    key-store-password: ${config.server.ssl.keyStorePassword || '${SSL_PASSWORD}'}
    key-store-type: PKCS12
`;
      }

      yaml += `
logging:
  level:
    root: ${config.logging.level.root}
    com.yourpackage: ${config.logging.level.app}
    org.hibernate.SQL: ${config.logging.level.sql}
  pattern:
    console: "${config.logging.pattern}"
`;

      if (config.customProperties.length > 0) {
        yaml += `\n# Custom Properties\n`;
        config.customProperties.forEach(p => {
          yaml += `${p.key}: ${p.value}\n`;
        });
      }

      return yaml;
    } else {
      let props = `# Spring Boot Application Configuration
# Generated by Spring Config Builder

spring.profiles.active=${config.profiles.join(',')}

# Datasource
spring.datasource.url=${config.datasource.url}
spring.datasource.username=${config.datasource.username}
spring.datasource.password=${config.datasource.password || '${DB_PASSWORD}'}
spring.datasource.driver-class-name=${config.datasource.driverClassName}
spring.datasource.hikari.maximum-pool-size=${config.datasource.hikari.maximumPoolSize}
spring.datasource.hikari.minimum-idle=${config.datasource.hikari.minimumIdle}
spring.datasource.hikari.connection-timeout=${config.datasource.hikari.connectionTimeout}

# JPA/Hibernate
spring.jpa.show-sql=${config.jpa.showSql}
spring.jpa.hibernate.ddl-auto=${config.jpa.hibernate.ddlAuto}
spring.jpa.properties.hibernate.dialect=${config.jpa.hibernate.dialect}
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${config.server.port}
server.servlet.context-path=${config.server.contextPath}
`;

      if (config.server.ssl.enabled) {
        props += `server.ssl.enabled=true
server.ssl.key-store=${config.server.ssl.keyStore}
server.ssl.key-store-password=${config.server.ssl.keyStorePassword || '${SSL_PASSWORD}'}
server.ssl.key-store-type=PKCS12
`;
      }

      props += `
# Logging
logging.level.root=${config.logging.level.root}
logging.level.com.yourpackage=${config.logging.level.app}
logging.level.org.hibernate.SQL=${config.logging.level.sql}
logging.pattern.console=${config.logging.pattern}
`;

      if (config.customProperties.length > 0) {
        props += `\n# Custom Properties\n`;
        config.customProperties.forEach(p => {
          props += `${p.key}=${p.value}\n`;
        });
      }

      return props;
    }
  }, [config, format]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generatedConfig);
    setSnackbar({ open: true, message: 'Copied to clipboard' });
  };

  const handleDownload = () => {
    const filename = format === 'yaml' ? 'application.yml' : 'application.properties';
    const blob = new Blob([generatedConfig], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const addCustomProperty = () => {
    setConfig({
      ...config,
      customProperties: [...config.customProperties, { key: 'custom.property', value: 'value' }],
    });
  };

  const removeCustomProperty = (index: number) => {
    setConfig({
      ...config,
      customProperties: config.customProperties.filter((_, i) => i !== index),
    });
  };

  const updateCustomProperty = (index: number, field: 'key' | 'value', value: string) => {
    setConfig({
      ...config,
      customProperties: config.customProperties.map((p, i) =>
        i === index ? { ...p, [field]: value } : p
      ),
    });
  };

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: '#0a0a0a' }}>
      <Paper elevation={0} sx={{ bgcolor: '#111', borderBottom: '1px solid #222', px: 3, py: 2 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
            <Link to="/"><IconButton size="small" sx={{ color: 'grey.500' }}><Home /></IconButton></Link>
            <Typography variant="h5" sx={{ color: 'white', fontWeight: 600 }}>Spring Boot Config Builder</Typography>
            <Chip label="Java" size="small" color="warning" />
          </Box>
          <Box sx={{ display: 'flex', gap: 1 }}>
            <Tooltip title="Download"><IconButton onClick={handleDownload} sx={{ color: 'grey.500' }}><Download /></IconButton></Tooltip>
            <Tooltip title="Copy"><IconButton onClick={handleCopy} sx={{ color: 'grey.500' }}><ContentCopy /></IconButton></Tooltip>
          </Box>
        </Box>
      </Paper>

      <Box sx={{ display: 'flex', height: 'calc(100vh - 70px)' }}>
        {/* Builder Panel */}
        <Box sx={{ flex: 1, p: 2, overflow: 'auto' }}>
          <Tabs value={format} onChange={(_, v) => setFormat(v)} sx={{ mb: 2 }}>
            <Tab value="yaml" label="YAML" sx={{ color: 'grey.400' }} />
            <Tab value="properties" label="Properties" sx={{ color: 'grey.400' }} />
          </Tabs>

          {/* Database Presets */}
          <Box sx={{ mb: 2 }}>
            <Typography variant="subtitle2" sx={{ color: 'grey.400', mb: 1 }}>Database Preset</Typography>
            <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
              {Object.keys(DATABASE_PRESETS).map(preset => (
                <Chip
                  key={preset}
                  label={preset.toUpperCase()}
                  onClick={() => applyDatabasePreset(preset as keyof typeof DATABASE_PRESETS)}
                  sx={{ cursor: 'pointer' }}
                />
              ))}
            </Box>
          </Box>

          {/* Server Config */}
          <Accordion defaultExpanded sx={{ bgcolor: '#111', border: '1px solid #222', mb: 2, '&:before': { display: 'none' } }}>
            <AccordionSummary expandIcon={<ExpandMore sx={{ color: 'grey.500' }} />}>
              <Typography sx={{ color: 'grey.300' }}>Server Configuration</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
                <TextField size="small" label="Port" type="number" value={config.server.port} onChange={(e) => setConfig({ ...config, server: { ...config.server, port: parseInt(e.target.value) || 8080 } })} sx={{ width: 120, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                <TextField size="small" label="Context Path" value={config.server.contextPath} onChange={(e) => setConfig({ ...config, server: { ...config.server, contextPath: e.target.value } })} sx={{ flex: 1, '& .MuiInputBase-root': { color: 'grey.300' } }} />
              </Box>
              <FormControlLabel
                control={<Switch checked={config.server.ssl.enabled} onChange={(e) => setConfig({ ...config, server: { ...config.server, ssl: { ...config.server.ssl, enabled: e.target.checked } } })} size="small" />}
                label={<Typography sx={{ color: 'grey.400', fontSize: 14 }}>Enable SSL</Typography>}
              />
              {config.server.ssl.enabled && (
                <Box sx={{ display: 'flex', gap: 2, mt: 2 }}>
                  <TextField size="small" label="Key Store Path" value={config.server.ssl.keyStore} onChange={(e) => setConfig({ ...config, server: { ...config.server, ssl: { ...config.server.ssl, keyStore: e.target.value } } })} sx={{ flex: 1, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                  <TextField size="small" label="Key Store Password" type="password" value={config.server.ssl.keyStorePassword} onChange={(e) => setConfig({ ...config, server: { ...config.server, ssl: { ...config.server.ssl, keyStorePassword: e.target.value } } })} sx={{ flex: 1, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                </Box>
              )}
            </AccordionDetails>
          </Accordion>

          {/* Datasource Config */}
          <Accordion defaultExpanded sx={{ bgcolor: '#111', border: '1px solid #222', mb: 2, '&:before': { display: 'none' } }}>
            <AccordionSummary expandIcon={<ExpandMore sx={{ color: 'grey.500' }} />}>
              <Typography sx={{ color: 'grey.300' }}>Datasource Configuration</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                <TextField size="small" label="JDBC URL" value={config.datasource.url} onChange={(e) => setConfig({ ...config, datasource: { ...config.datasource, url: e.target.value } })} fullWidth sx={{ '& .MuiInputBase-root': { color: 'grey.300' } }} />
                <Box sx={{ display: 'flex', gap: 2 }}>
                  <TextField size="small" label="Username" value={config.datasource.username} onChange={(e) => setConfig({ ...config, datasource: { ...config.datasource, username: e.target.value } })} sx={{ flex: 1, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                  <TextField size="small" label="Password" type="password" value={config.datasource.password} onChange={(e) => setConfig({ ...config, datasource: { ...config.datasource, password: e.target.value } })} sx={{ flex: 1, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                </Box>
                <TextField size="small" label="Driver Class Name" value={config.datasource.driverClassName} onChange={(e) => setConfig({ ...config, datasource: { ...config.datasource, driverClassName: e.target.value } })} fullWidth sx={{ '& .MuiInputBase-root': { color: 'grey.300' } }} />
                <Typography variant="subtitle2" sx={{ color: 'grey.500', mt: 1 }}>HikariCP Pool Settings</Typography>
                <Box sx={{ display: 'flex', gap: 2 }}>
                  <TextField size="small" label="Max Pool Size" type="number" value={config.datasource.hikari.maximumPoolSize} onChange={(e) => setConfig({ ...config, datasource: { ...config.datasource, hikari: { ...config.datasource.hikari, maximumPoolSize: parseInt(e.target.value) || 10 } } })} sx={{ flex: 1, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                  <TextField size="small" label="Min Idle" type="number" value={config.datasource.hikari.minimumIdle} onChange={(e) => setConfig({ ...config, datasource: { ...config.datasource, hikari: { ...config.datasource.hikari, minimumIdle: parseInt(e.target.value) || 5 } } })} sx={{ flex: 1, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                  <TextField size="small" label="Connection Timeout (ms)" type="number" value={config.datasource.hikari.connectionTimeout} onChange={(e) => setConfig({ ...config, datasource: { ...config.datasource, hikari: { ...config.datasource.hikari, connectionTimeout: parseInt(e.target.value) || 30000 } } })} sx={{ flex: 1, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                </Box>
              </Box>
            </AccordionDetails>
          </Accordion>

          {/* JPA Config */}
          <Accordion defaultExpanded sx={{ bgcolor: '#111', border: '1px solid #222', mb: 2, '&:before': { display: 'none' } }}>
            <AccordionSummary expandIcon={<ExpandMore sx={{ color: 'grey.500' }} />}>
              <Typography sx={{ color: 'grey.300' }}>JPA / Hibernate Configuration</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
                <FormControl size="small" sx={{ minWidth: 200 }}>
                  <InputLabel sx={{ color: 'grey.500' }}>DDL Auto</InputLabel>
                  <Select value={config.jpa.hibernate.ddlAuto} label="DDL Auto" onChange={(e) => setConfig({ ...config, jpa: { ...config.jpa, hibernate: { ...config.jpa.hibernate, ddlAuto: e.target.value } } })} sx={{ color: 'grey.300' }}>
                    <MenuItem value="none">none</MenuItem>
                    <MenuItem value="validate">validate</MenuItem>
                    <MenuItem value="update">update</MenuItem>
                    <MenuItem value="create">create</MenuItem>
                    <MenuItem value="create-drop">create-drop</MenuItem>
                  </Select>
                </FormControl>
                <FormControlLabel
                  control={<Switch checked={config.jpa.showSql} onChange={(e) => setConfig({ ...config, jpa: { ...config.jpa, showSql: e.target.checked } })} size="small" />}
                  label={<Typography sx={{ color: 'grey.400', fontSize: 14 }}>Show SQL</Typography>}
                />
              </Box>
              <TextField size="small" label="Hibernate Dialect" value={config.jpa.hibernate.dialect} onChange={(e) => setConfig({ ...config, jpa: { ...config.jpa, hibernate: { ...config.jpa.hibernate, dialect: e.target.value } } })} fullWidth sx={{ '& .MuiInputBase-root': { color: 'grey.300' } }} />
            </AccordionDetails>
          </Accordion>

          {/* Logging Config */}
          <Accordion sx={{ bgcolor: '#111', border: '1px solid #222', mb: 2, '&:before': { display: 'none' } }}>
            <AccordionSummary expandIcon={<ExpandMore sx={{ color: 'grey.500' }} />}>
              <Typography sx={{ color: 'grey.300' }}>Logging Configuration</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Box sx={{ display: 'flex', gap: 2, mb: 2 }}>
                <FormControl size="small" sx={{ minWidth: 120 }}>
                  <InputLabel sx={{ color: 'grey.500' }}>Root Level</InputLabel>
                  <Select value={config.logging.level.root} label="Root Level" onChange={(e) => setConfig({ ...config, logging: { ...config.logging, level: { ...config.logging.level, root: e.target.value } } })} sx={{ color: 'grey.300' }}>
                    {['TRACE', 'DEBUG', 'INFO', 'WARN', 'ERROR'].map(l => <MenuItem key={l} value={l}>{l}</MenuItem>)}
                  </Select>
                </FormControl>
                <FormControl size="small" sx={{ minWidth: 120 }}>
                  <InputLabel sx={{ color: 'grey.500' }}>App Level</InputLabel>
                  <Select value={config.logging.level.app} label="App Level" onChange={(e) => setConfig({ ...config, logging: { ...config.logging, level: { ...config.logging.level, app: e.target.value } } })} sx={{ color: 'grey.300' }}>
                    {['TRACE', 'DEBUG', 'INFO', 'WARN', 'ERROR'].map(l => <MenuItem key={l} value={l}>{l}</MenuItem>)}
                  </Select>
                </FormControl>
                <FormControl size="small" sx={{ minWidth: 120 }}>
                  <InputLabel sx={{ color: 'grey.500' }}>SQL Level</InputLabel>
                  <Select value={config.logging.level.sql} label="SQL Level" onChange={(e) => setConfig({ ...config, logging: { ...config.logging, level: { ...config.logging.level, sql: e.target.value } } })} sx={{ color: 'grey.300' }}>
                    {['TRACE', 'DEBUG', 'INFO', 'WARN', 'ERROR'].map(l => <MenuItem key={l} value={l}>{l}</MenuItem>)}
                  </Select>
                </FormControl>
              </Box>
            </AccordionDetails>
          </Accordion>

          {/* Custom Properties */}
          <Accordion sx={{ bgcolor: '#111', border: '1px solid #222', mb: 2, '&:before': { display: 'none' } }}>
            <AccordionSummary expandIcon={<ExpandMore sx={{ color: 'grey.500' }} />}>
              <Typography sx={{ color: 'grey.300' }}>Custom Properties</Typography>
            </AccordionSummary>
            <AccordionDetails>
              {config.customProperties.map((prop, index) => (
                <Box key={index} sx={{ display: 'flex', gap: 2, mb: 1 }}>
                  <TextField size="small" label="Key" value={prop.key} onChange={(e) => updateCustomProperty(index, 'key', e.target.value)} sx={{ flex: 1, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                  <TextField size="small" label="Value" value={prop.value} onChange={(e) => updateCustomProperty(index, 'value', e.target.value)} sx={{ flex: 1, '& .MuiInputBase-root': { color: 'grey.300' } }} />
                  <IconButton size="small" onClick={() => removeCustomProperty(index)} sx={{ color: 'grey.500' }}><Delete /></IconButton>
                </Box>
              ))}
              <Button startIcon={<Add />} onClick={addCustomProperty} sx={{ color: 'grey.500' }}>Add Property</Button>
            </AccordionDetails>
          </Accordion>
        </Box>

        {/* Output Panel */}
        <Box sx={{ width: 500, borderLeft: '1px solid #222', display: 'flex', flexDirection: 'column' }}>
          <Box sx={{ p: 2, borderBottom: '1px solid #222' }}>
            <Typography variant="subtitle2" sx={{ color: 'grey.400' }}>
              {format === 'yaml' ? 'application.yml' : 'application.properties'}
            </Typography>
          </Box>
          <Box sx={{ flex: 1, p: 2, overflow: 'auto' }}>
            <Paper sx={{ bgcolor: '#0a0a0a', p: 2, border: '1px solid #333', height: '100%' }}>
              <Typography component="pre" sx={{ fontFamily: 'monospace', fontSize: 11, color: '#d4d4d4', m: 0, whiteSpace: 'pre-wrap' }}>
                {generatedConfig}
              </Typography>
            </Paper>
          </Box>
        </Box>
      </Box>

      <Snackbar open={snackbar.open} autoHideDuration={2000} onClose={() => setSnackbar({ ...snackbar, open: false })} message={snackbar.message} />
    </Box>
  );
}
