import { Link } from 'react-router-dom';
import { useState } from 'react';
import {
  Map as MapIcon,
  Search as SearchIcon,
  Image as ImageIcon,
  Code as CodeIcon,
  Layers,
  Database,
  Palette,
  FileJson,
  Regex,
  Key,
  Binary,
  Fingerprint,
  Clock,
  GitCompare,
  Brush,
  FileText,
  Users,
  Globe,
  Server,
  FileCode,
  Scissors,
  Container,
  Cloud,
  Leaf,
  Network,
  TableProperties,
  FileSpreadsheet,
  Link as LinkIcon,
  Timer,
  Braces,
  ScrollText,
  Component,
  ArrowLeftRight,
  FunctionSquare,
  Sparkles,
  Filter,
  // New icons for additional tools
  Lock,
  FileCode2,
  Type,
  KeyRound,
  FileType,
  Wifi,
  Shield,
  GitBranch,
  Cylinder,
  HardDrive,
  FileX,
  GitPullRequest,
  Boxes,
  Package,
  ShieldCheck,
  Workflow,
  Table,
  DatabaseZap,
  Plug,
  Gauge,
  FlaskConical,
  // Office tools icons
  QrCode,
  Receipt,
  Timer as TimerIcon,
  KanbanSquare,
  ArrowRightLeft,
  Mail,
  Globe2,
  Wallet,
  TextCursor,
  Briefcase,
  Hash,
  HardDriveDownload,
  NotebookPen,
  Calculator,
  DollarSign,
  Hourglass,
  AlarmClock,
  StickyNote,
  ListChecks,
  Scale,
  // New tool icons
  BookOpen,
  GraduationCap,
  FlaskRound,
  Atom,
  Target,
  Keyboard,
  Cpu,
  BarChart3,
  GitMerge,
  Terminal,
  Eye,
  Radio,
  ScanText,
  Monitor,
  Presentation,
  Calendar,
  Pen,
  Table2,
  ClipboardList,
  Landmark,
  Barcode,
  GitCompareArrows,
  // New batch icons
  Ship,
  Play,
  Activity,
  LayoutDashboard,
  Box,
  Settings,
  Zap,
  MessageSquare,
  Tag,
  GitCommitHorizontal,
  LayoutGrid,
  Move,
  Wand2,
  Smartphone,
  EyeOff,
  Blocks,
  FileSearch,
  Route,
  Bot,
  Grid3x3,
  // Geospatial tools icons
  Compass,
  MapPin,
  FileUp,
  FormInput,
} from 'lucide-react';

interface Tool {
  title: string;
  description: string;
  icon: React.ReactNode;
  gradient: string;
  to: string;
  category: string;
  isNew?: boolean;
}

const categories = [
  { id: 'all', label: 'All Tools', icon: <Layers className="w-4 h-4" /> },
  { id: 'learning', label: 'Learning', icon: <GraduationCap className="w-4 h-4" /> },
  { id: 'gis', label: 'GIS & Maps', icon: <MapIcon className="w-4 h-4" /> },
  { id: 'data', label: 'Data & API', icon: <Database className="w-4 h-4" /> },
  { id: 'code', label: 'Code Gen', icon: <CodeIcon className="w-4 h-4" /> },
  { id: 'converter', label: 'Converters', icon: <ArrowRightLeft className="w-4 h-4" /> },
  { id: 'devops', label: 'DevOps', icon: <Container className="w-4 h-4" /> },
  { id: 'security', label: 'Security', icon: <Shield className="w-4 h-4" /> },
  { id: 'testing', label: 'Testing', icon: <FlaskConical className="w-4 h-4" /> },
  { id: 'frontend', label: 'Frontend', icon: <Monitor className="w-4 h-4" /> },
  { id: 'reference', label: 'Reference', icon: <BookOpen className="w-4 h-4" /> },
  { id: 'office', label: 'Office', icon: <Briefcase className="w-4 h-4" /> },
  { id: 'govtforms', label: 'Govt Forms', icon: <Landmark className="w-4 h-4" /> },
  { id: 'utils', label: 'Utilities', icon: <Sparkles className="w-4 h-4" /> },
];

const tools: Tool[] = [
  // GIS & Maps
  {
    title: 'ArcGIS Map Builder',
    description: 'Visual map builder with layers, widgets & code export',
    icon: <MapIcon className="w-5 h-5" />,
    gradient: 'from-emerald-500 to-teal-600',
    to: '/arcgis-map',
    category: 'gis',
  },
  {
    title: 'Map Draw Tool',
    description: 'Draw points, polygons & circles on map, export as PNG/JPG',
    icon: <Brush className="w-5 h-5" />,
    gradient: 'from-cyan-500 to-teal-600',
    to: '/map-draw',
    category: 'gis',
    isNew: true,
  },
  {
    title: 'GeoServer REST Builder',
    description: 'Generate cURL/fetch/Python for GeoServer REST API operations',
    icon: <Server className="w-5 h-5" />,
    gradient: 'from-violet-500 to-purple-600',
    to: '/geoserver-rest-builder',
    category: 'gis',
    isNew: true,
  },
  {
    title: 'SLD Style Generator',
    description: 'Visual builder for Styled Layer Descriptor XML files',
    icon: <Palette className="w-5 h-5" />,
    gradient: 'from-pink-500 to-rose-600',
    to: '/sld-style-generator',
    category: 'gis',
    isNew: true,
  },
  {
    title: 'CQL Filter Builder',
    description: 'Build CQL/ECQL filters for GeoServer WMS/WFS requests',
    icon: <Filter className="w-5 h-5" />,
    gradient: 'from-amber-500 to-orange-600',
    to: '/cql-filter-builder',
    category: 'gis',
    isNew: true,
  },
  {
    title: 'WMS/WFS/WCS Builder',
    description: 'Construct OGC WMS, WFS, WCS & WMTS service request URLs',
    icon: <Globe className="w-5 h-5" />,
    gradient: 'from-blue-500 to-cyan-600',
    to: '/wms-wfs-builder',
    category: 'gis',
    isNew: true,
  },
  {
    title: 'ArcGIS Query Builder',
    description: 'Build ArcGIS REST API query URLs with spatial & statistics support',
    icon: <Database className="w-5 h-5" />,
    gradient: 'from-indigo-500 to-blue-600',
    to: '/arcgis-query-builder',
    category: 'gis',
    isNew: true,
  },
  {
    title: 'ArcGIS Service URL',
    description: 'Generate ArcGIS Server REST URLs with code snippets for all service types',
    icon: <Server className="w-5 h-5" />,
    gradient: 'from-teal-500 to-emerald-600',
    to: '/arcgis-service-url',
    category: 'gis',
    isNew: true,
  },
  {
    title: 'Arcade Expression Builder',
    description: 'Build ArcGIS Arcade expressions with syntax reference & examples',
    icon: <FunctionSquare className="w-5 h-5" />,
    gradient: 'from-orange-500 to-red-600',
    to: '/arcade-expression-builder',
    category: 'gis',
    isNew: true,
  },
  {
    title: 'GeoJSON Editor',
    description: 'Edit, validate & convert GeoJSON with structure preview',
    icon: <FileJson className="w-5 h-5" />,
    gradient: 'from-green-500 to-emerald-600',
    to: '/geojson-editor',
    category: 'gis',
    isNew: true,
  },
  {
    title: 'Coordinate Converter',
    description: 'Convert between WGS84, UTM, MGRS & Web Mercator coordinates',
    icon: <Compass className="w-5 h-5" />,
    gradient: 'from-sky-500 to-blue-600',
    to: '/coordinate-converter',
    category: 'gis',
    isNew: true,
  },
  {
    title: 'Bounding Box Generator',
    description: 'Generate bbox in multiple formats with presets for common areas',
    icon: <MapPin className="w-5 h-5" />,
    gradient: 'from-rose-500 to-pink-600',
    to: '/bbox-generator',
    category: 'gis',
    isNew: true,
  },
  {
    title: 'PostGIS Query Builder',
    description: 'Build PostGIS spatial SQL queries with ST_ function reference',
    icon: <Database className="w-5 h-5" />,
    gradient: 'from-blue-600 to-indigo-700',
    to: '/postgis-query-builder',
    category: 'gis',
    isNew: true,
  },
  {
    title: 'WKT/GeoJSON Converter',
    description: 'Convert between WKT and GeoJSON with SRID/EWKT support',
    icon: <ArrowRightLeft className="w-5 h-5" />,
    gradient: 'from-purple-500 to-violet-600',
    to: '/wkt-geojson-converter',
    category: 'gis',
    isNew: true,
  },
  {
    title: 'Map Tile URL Builder',
    description: 'Build XYZ, TMS, WMTS & Quadkey tile URLs with tile calculator',
    icon: <Globe className="w-5 h-5" />,
    gradient: 'from-cyan-500 to-teal-600',
    to: '/map-tile-url-builder',
    category: 'gis',
    isNew: true,
  },
  {
    title: 'EPSG/CRS Reference',
    description: 'Search EPSG codes with proj4 strings & coordinate system details',
    icon: <Compass className="w-5 h-5" />,
    gradient: 'from-amber-500 to-yellow-600',
    to: '/epsg-crs-reference',
    category: 'gis',
    isNew: true,
  },
  {
    title: 'Shapefile & Style Builder',
    description: 'Convert JSON/CSV to GeoJSON with SLD styling for GeoServer publish',
    icon: <FileUp className="w-5 h-5" />,
    gradient: 'from-emerald-500 to-teal-600',
    to: '/shapefile-style-builder',
    category: 'gis',
    isNew: true,
  },
  // Data & API
  {
    title: 'ES Query Designer',
    description: 'Visual Elasticsearch query builder',
    icon: <SearchIcon className="w-5 h-5" />,
    gradient: 'from-blue-500 to-indigo-600',
    to: '/es-query',
    category: 'data',
  },
  {
    title: 'API Request Builder',
    description: 'REST API client with history',
    icon: <Globe className="w-5 h-5" />,
    gradient: 'from-cyan-500 to-blue-600',
    to: '/api-client',
    category: 'data',
    isNew: true,
  },
  {
    title: 'JSON/YAML Editor',
    description: 'Validate, format & convert',
    icon: <FileJson className="w-5 h-5" />,
    gradient: 'from-amber-500 to-orange-600',
    to: '/json-yaml',
    category: 'data',
    isNew: true,
  },
  {
    title: 'SQL Query Builder',
    description: 'Visual SQL query constructor',
    icon: <Database className="w-5 h-5" />,
    gradient: 'from-blue-600 to-indigo-700',
    to: '/sql',
    category: 'data',
    isNew: true,
  },
  {
    title: 'ES Index Mapping',
    description: 'Design ES index mappings',
    icon: <SearchIcon className="w-5 h-5" />,
    gradient: 'from-yellow-500 to-orange-500',
    to: '/es-mapping',
    category: 'data',
    isNew: true,
  },
  {
    title: 'Cypher Query Builder',
    description: 'Neo4j Cypher query builder',
    icon: <Network className="w-5 h-5" />,
    gradient: 'from-blue-400 to-cyan-500',
    to: '/cypher',
    category: 'data',
    isNew: true,
  },
  {
    title: 'JSONPath Tester',
    description: 'Test JSONPath expressions',
    icon: <Braces className="w-5 h-5" />,
    gradient: 'from-orange-400 to-red-500',
    to: '/jsonpath',
    category: 'data',
    isNew: true,
  },
  // Code Generation
  {
    title: 'Icon Generator Pro',
    description: '15K+ icons with custom shapes',
    icon: <ImageIcon className="w-5 h-5" />,
    gradient: 'from-purple-500 to-pink-600',
    to: '/icons-generator',
    category: 'code',
  },
  {
    title: 'React Visual Builder',
    description: 'Drag-and-drop MUI components',
    icon: <CodeIcon className="w-5 h-5" />,
    gradient: 'from-orange-500 to-red-600',
    to: '/visual-builder',
    category: 'code',
  },
  {
    title: 'React Component Gen',
    description: 'Generate React components',
    icon: <Component className="w-5 h-5" />,
    gradient: 'from-cyan-400 to-blue-500',
    to: '/react-gen',
    category: 'code',
    isNew: true,
  },
  {
    title: 'JPA Entity Generator',
    description: 'Generate JPA entities & repos',
    icon: <TableProperties className="w-5 h-5" />,
    gradient: 'from-indigo-500 to-purple-600',
    to: '/jpa-entity',
    category: 'code',
    isNew: true,
  },
  {
    title: 'MapStruct Mapper',
    description: 'DTO-Entity mapper generator',
    icon: <ArrowLeftRight className="w-5 h-5" />,
    gradient: 'from-violet-500 to-fuchsia-600',
    to: '/mapstruct',
    category: 'code',
    isNew: true,
  },
  {
    title: 'PostgreSQL Functions',
    description: 'PL/pgSQL function builder',
    icon: <FunctionSquare className="w-5 h-5" />,
    gradient: 'from-blue-600 to-indigo-700',
    to: '/postgresql',
    category: 'code',
    isNew: true,
  },
  {
    title: 'OpenAPI Editor',
    description: 'Visual API documentation',
    icon: <FileCode className="w-5 h-5" />,
    gradient: 'from-emerald-500 to-green-600',
    to: '/openapi',
    category: 'code',
    isNew: true,
  },
  {
    title: 'DB Migration Gen',
    description: 'Flyway/Liquibase scripts',
    icon: <FileSpreadsheet className="w-5 h-5" />,
    gradient: 'from-teal-500 to-cyan-600',
    to: '/migration',
    category: 'code',
    isNew: true,
  },
  // DevOps
  {
    title: 'Docker Compose',
    description: 'Visual docker-compose builder',
    icon: <Container className="w-5 h-5" />,
    gradient: 'from-blue-400 to-cyan-500',
    to: '/docker',
    category: 'devops',
    isNew: true,
  },
  {
    title: 'Kubernetes YAML',
    description: 'K8s manifest generator',
    icon: <Cloud className="w-5 h-5" />,
    gradient: 'from-blue-500 to-violet-600',
    to: '/k8s',
    category: 'devops',
    isNew: true,
  },
  {
    title: 'Nginx Config',
    description: 'nginx.conf generator',
    icon: <Server className="w-5 h-5" />,
    gradient: 'from-green-500 to-emerald-600',
    to: '/nginx',
    category: 'devops',
    isNew: true,
  },
  {
    title: 'Spring Boot Config',
    description: 'application.yml builder',
    icon: <Leaf className="w-5 h-5" />,
    gradient: 'from-green-500 to-lime-600',
    to: '/spring-config',
    category: 'devops',
    isNew: true,
  },
  {
    title: 'Logback Config',
    description: 'Logging configuration',
    icon: <ScrollText className="w-5 h-5" />,
    gradient: 'from-red-500 to-pink-600',
    to: '/logback',
    category: 'devops',
    isNew: true,
  },
  {
    title: 'JDBC Connection',
    description: 'Connection string builder',
    icon: <LinkIcon className="w-5 h-5" />,
    gradient: 'from-slate-500 to-zinc-600',
    to: '/jdbc',
    category: 'devops',
    isNew: true,
  },
  // Utilities
  {
    title: 'Regex Builder',
    description: 'Visual regex constructor',
    icon: <Regex className="w-5 h-5" />,
    gradient: 'from-rose-500 to-pink-600',
    to: '/regex',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'JWT Debugger',
    description: 'Decode & inspect tokens',
    icon: <Key className="w-5 h-5" />,
    gradient: 'from-violet-500 to-purple-600',
    to: '/jwt',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Base64 Encoder',
    description: 'Encode/decode Base64',
    icon: <Binary className="w-5 h-5" />,
    gradient: 'from-slate-500 to-gray-600',
    to: '/base64',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'UUID & Hash Gen',
    description: 'Generate UUIDs & hashes',
    icon: <Fingerprint className="w-5 h-5" />,
    gradient: 'from-indigo-500 to-blue-600',
    to: '/uuid',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Cron Builder',
    description: 'Cron expression generator',
    icon: <Clock className="w-5 h-5" />,
    gradient: 'from-teal-500 to-emerald-600',
    to: '/cron',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Timestamp Converter',
    description: 'Convert date/time formats',
    icon: <Timer className="w-5 h-5" />,
    gradient: 'from-amber-500 to-yellow-600',
    to: '/timestamp',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Diff Viewer',
    description: 'Compare text & code',
    icon: <GitCompare className="w-5 h-5" />,
    gradient: 'from-lime-500 to-green-600',
    to: '/diff',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Color Palette',
    description: 'Generate color palettes',
    icon: <Palette className="w-5 h-5" />,
    gradient: 'from-fuchsia-500 to-pink-600',
    to: '/colors',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'CSS Generator',
    description: 'Gradients, shadows & more',
    icon: <Brush className="w-5 h-5" />,
    gradient: 'from-sky-500 to-cyan-600',
    to: '/css',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Markdown Editor',
    description: 'Live preview editor',
    icon: <FileText className="w-5 h-5" />,
    gradient: 'from-stone-500 to-neutral-600',
    to: '/markdown',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Data Faker',
    description: 'Generate fake test data',
    icon: <Users className="w-5 h-5" />,
    gradient: 'from-yellow-500 to-amber-600',
    to: '/faker',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Image Converter',
    description: 'Convert & resize images',
    icon: <Scissors className="w-5 h-5" />,
    gradient: 'from-red-500 to-rose-600',
    to: '/image',
    category: 'utils',
    isNew: true,
  },
  // NEW TOOLS - Utilities
  {
    title: 'URL Encoder',
    description: 'Encode/decode URLs',
    icon: <Lock className="w-5 h-5" />,
    gradient: 'from-emerald-500 to-green-600',
    to: '/url-encoder',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'HTML Entity Encoder',
    description: 'Encode/decode HTML entities',
    icon: <FileCode2 className="w-5 h-5" />,
    gradient: 'from-orange-500 to-amber-600',
    to: '/html-entity',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Text Case Converter',
    description: 'Convert between case styles',
    icon: <Type className="w-5 h-5" />,
    gradient: 'from-pink-500 to-rose-600',
    to: '/text-case',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Password Generator',
    description: 'Generate secure passwords',
    icon: <KeyRound className="w-5 h-5" />,
    gradient: 'from-red-600 to-rose-700',
    to: '/password',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Lorem Ipsum',
    description: 'Generate placeholder text',
    icon: <FileType className="w-5 h-5" />,
    gradient: 'from-gray-500 to-slate-600',
    to: '/lorem-ipsum',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'IP Calculator',
    description: 'Subnet & CIDR calculator',
    icon: <Wifi className="w-5 h-5" />,
    gradient: 'from-cyan-500 to-teal-600',
    to: '/ip-calc',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'SSL Certificate Decoder',
    description: 'Decode X.509 certificates',
    icon: <Shield className="w-5 h-5" />,
    gradient: 'from-green-600 to-emerald-700',
    to: '/ssl-decoder',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'ASCII Table Generator',
    description: 'Generate ASCII tables',
    icon: <Table className="w-5 h-5" />,
    gradient: 'from-stone-500 to-zinc-600',
    to: '/ascii-table',
    category: 'utils',
    isNew: true,
  },
  // NEW TOOLS - Data & API
  {
    title: 'GraphQL Builder',
    description: 'Visual GraphQL query builder',
    icon: <GitBranch className="w-5 h-5" />,
    gradient: 'from-pink-600 to-fuchsia-700',
    to: '/graphql',
    category: 'data',
    isNew: true,
  },
  {
    title: 'MongoDB Builder',
    description: 'MongoDB query builder',
    icon: <Cylinder className="w-5 h-5" />,
    gradient: 'from-green-600 to-emerald-700',
    to: '/mongodb',
    category: 'data',
    isNew: true,
  },
  {
    title: 'Redis Commands',
    description: 'Redis command builder',
    icon: <HardDrive className="w-5 h-5" />,
    gradient: 'from-red-600 to-rose-700',
    to: '/redis',
    category: 'data',
    isNew: true,
  },
  // NEW TOOLS - Code Generation
  {
    title: 'pom.xml Generator',
    description: 'Maven POM file generator',
    icon: <Package className="w-5 h-5" />,
    gradient: 'from-orange-600 to-red-700',
    to: '/pom',
    category: 'code',
    isNew: true,
  },
  {
    title: 'Spring Security Config',
    description: 'Security configuration builder',
    icon: <ShieldCheck className="w-5 h-5" />,
    gradient: 'from-green-500 to-teal-600',
    to: '/spring-security',
    category: 'code',
    isNew: true,
  },
  {
    title: 'Mermaid Editor',
    description: 'Mermaid diagram editor',
    icon: <Workflow className="w-5 h-5" />,
    gradient: 'from-pink-500 to-purple-600',
    to: '/mermaid',
    category: 'code',
    isNew: true,
  },
  {
    title: 'ERD Builder',
    description: 'Database schema designer',
    icon: <DatabaseZap className="w-5 h-5" />,
    gradient: 'from-indigo-500 to-violet-600',
    to: '/erd',
    category: 'code',
    isNew: true,
  },
  // NEW TOOLS - DevOps
  {
    title: 'Gitignore Generator',
    description: 'Generate .gitignore files',
    icon: <FileX className="w-5 h-5" />,
    gradient: 'from-gray-600 to-slate-700',
    to: '/gitignore',
    category: 'devops',
    isNew: true,
  },
  {
    title: 'GitHub Actions Builder',
    description: 'CI/CD workflow generator',
    icon: <GitPullRequest className="w-5 h-5" />,
    gradient: 'from-purple-600 to-indigo-700',
    to: '/github-actions',
    category: 'devops',
    isNew: true,
  },
  {
    title: 'Terraform Builder',
    description: 'Generate Terraform configs',
    icon: <Boxes className="w-5 h-5" />,
    gradient: 'from-violet-600 to-purple-700',
    to: '/terraform',
    category: 'devops',
    isNew: true,
  },
  // NEW TOOLS - Testing
  {
    title: 'Mock API Server',
    description: 'Create mock REST endpoints',
    icon: <Server className="w-5 h-5" />,
    gradient: 'from-cyan-600 to-blue-700',
    to: '/mock-api',
    category: 'testing',
    isNew: true,
  },
  {
    title: 'WebSocket Tester',
    description: 'Test WebSocket connections',
    icon: <Plug className="w-5 h-5" />,
    gradient: 'from-yellow-500 to-amber-600',
    to: '/websocket',
    category: 'testing',
    isNew: true,
  },
  {
    title: 'Load Test Config',
    description: 'Generate load test scripts',
    icon: <Gauge className="w-5 h-5" />,
    gradient: 'from-red-500 to-orange-600',
    to: '/load-test',
    category: 'testing',
    isNew: true,
  },
  // Office Tools
  {
    title: 'QR Code Generator',
    description: 'Create QR codes for URLs, text, WiFi',
    icon: <QrCode className="w-5 h-5" />,
    gradient: 'from-violet-500 to-purple-600',
    to: '/qr-generator',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Invoice Generator',
    description: 'Create professional invoices',
    icon: <Receipt className="w-5 h-5" />,
    gradient: 'from-emerald-500 to-green-600',
    to: '/invoice-generator',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Pomodoro Timer',
    description: 'Focus timer with work/break intervals',
    icon: <TimerIcon className="w-5 h-5" />,
    gradient: 'from-red-500 to-rose-600',
    to: '/pomodoro',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Kanban Board',
    description: 'Drag-and-drop task management',
    icon: <KanbanSquare className="w-5 h-5" />,
    gradient: 'from-blue-500 to-indigo-600',
    to: '/kanban',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Unit Converter',
    description: 'Convert length, weight, temperature & more',
    icon: <ArrowRightLeft className="w-5 h-5" />,
    gradient: 'from-amber-500 to-orange-600',
    to: '/unit-converter',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Email Signature',
    description: 'Generate professional email signatures',
    icon: <Mail className="w-5 h-5" />,
    gradient: 'from-pink-500 to-rose-600',
    to: '/email-signature',
    category: 'office',
    isNew: true,
  },
  {
    title: 'World Clock',
    description: 'Track time across multiple timezones',
    icon: <Globe2 className="w-5 h-5" />,
    gradient: 'from-cyan-500 to-blue-600',
    to: '/world-clock',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Expense Tracker',
    description: 'Track income & expenses by category',
    icon: <Wallet className="w-5 h-5" />,
    gradient: 'from-green-500 to-emerald-600',
    to: '/expense-tracker',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Character Counter',
    description: 'Count characters, words & reading time',
    icon: <TextCursor className="w-5 h-5" />,
    gradient: 'from-purple-500 to-violet-600',
    to: '/character-counter',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Hash Generator',
    description: 'Generate MD5, SHA-256, SHA-512 hashes',
    icon: <Hash className="w-5 h-5" />,
    gradient: 'from-indigo-500 to-purple-600',
    to: '/hash-generator',
    category: 'office',
    isNew: true,
  },
  {
    title: 'File Size Calculator',
    description: 'Convert between file size units',
    icon: <HardDriveDownload className="w-5 h-5" />,
    gradient: 'from-cyan-500 to-teal-600',
    to: '/file-size',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Meeting Notes',
    description: 'Create structured meeting notes',
    icon: <NotebookPen className="w-5 h-5" />,
    gradient: 'from-amber-500 to-orange-600',
    to: '/meeting-notes',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Budget Planner',
    description: 'Plan and track your budget',
    icon: <Calculator className="w-5 h-5" />,
    gradient: 'from-emerald-500 to-green-600',
    to: '/budget-planner',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Salary Calculator',
    description: 'Calculate take-home pay & taxes',
    icon: <DollarSign className="w-5 h-5" />,
    gradient: 'from-green-500 to-teal-600',
    to: '/salary-calculator',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Countdown Timer',
    description: 'Countdown to important events',
    icon: <Hourglass className="w-5 h-5" />,
    gradient: 'from-rose-500 to-red-600',
    to: '/countdown',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Stopwatch',
    description: 'Stopwatch with lap tracking',
    icon: <AlarmClock className="w-5 h-5" />,
    gradient: 'from-sky-500 to-blue-600',
    to: '/stopwatch',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Notepad',
    description: 'Simple note-taking with persistence',
    icon: <StickyNote className="w-5 h-5" />,
    gradient: 'from-yellow-500 to-amber-600',
    to: '/notepad',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Checklist',
    description: 'Create and manage checklists',
    icon: <ListChecks className="w-5 h-5" />,
    gradient: 'from-teal-500 to-cyan-600',
    to: '/checklist',
    category: 'office',
    isNew: true,
  },
  {
    title: 'BMI Calculator',
    description: 'Calculate Body Mass Index',
    icon: <Scale className="w-5 h-5" />,
    gradient: 'from-pink-500 to-fuchsia-600',
    to: '/bmi',
    category: 'office',
    isNew: true,
  },
  // Students & Learning Tools
  {
    title: 'Flashcard Maker',
    description: 'Create & review flashcards with spaced repetition',
    icon: <BookOpen className="w-5 h-5" />,
    gradient: 'from-blue-500 to-indigo-600',
    to: '/flashcard-maker',
    category: 'learning',
    isNew: true,
  },
  {
    title: 'GPA Calculator',
    description: 'Calculate semester & cumulative GPA',
    icon: <GraduationCap className="w-5 h-5" />,
    gradient: 'from-emerald-500 to-green-600',
    to: '/gpa-calculator',
    category: 'learning',
    isNew: true,
  },
  {
    title: 'Citation Generator',
    description: 'Generate APA, MLA, Chicago citations',
    icon: <FileText className="w-5 h-5" />,
    gradient: 'from-amber-500 to-orange-600',
    to: '/citation-generator',
    category: 'learning',
    isNew: true,
  },
  {
    title: 'Algorithm Visualizer',
    description: 'Visualize sorting algorithms step by step',
    icon: <BarChart3 className="w-5 h-5" />,
    gradient: 'from-purple-500 to-violet-600',
    to: '/algorithm-visualizer',
    category: 'learning',
    isNew: true,
  },
  {
    title: 'Data Structure Visualizer',
    description: 'Interactive Stack, Queue, LinkedList, BST',
    icon: <FlaskRound className="w-5 h-5" />,
    gradient: 'from-cyan-500 to-blue-600',
    to: '/data-structure-visualizer',
    category: 'learning',
    isNew: true,
  },
  {
    title: 'LaTeX Math Editor',
    description: 'Write & preview LaTeX math expressions',
    icon: <FunctionSquare className="w-5 h-5" />,
    gradient: 'from-teal-500 to-emerald-600',
    to: '/latex-math-editor',
    category: 'learning',
    isNew: true,
  },
  {
    title: 'Code Snippet Runner',
    description: 'Run JavaScript code in a sandbox',
    icon: <Terminal className="w-5 h-5" />,
    gradient: 'from-green-500 to-lime-600',
    to: '/code-snippet-runner',
    category: 'learning',
    isNew: true,
  },
  {
    title: 'Typing Speed Test',
    description: 'Test your typing speed & accuracy',
    icon: <Keyboard className="w-5 h-5" />,
    gradient: 'from-rose-500 to-pink-600',
    to: '/typing-speed-test',
    category: 'learning',
    isNew: true,
  },
  {
    title: 'Number Base Converter',
    description: 'Convert between binary, octal, decimal, hex',
    icon: <Binary className="w-5 h-5" />,
    gradient: 'from-indigo-500 to-purple-600',
    to: '/number-base-converter',
    category: 'learning',
    isNew: true,
  },
  {
    title: 'Bitwise Calculator',
    description: 'Interactive bitwise operations & visualization',
    icon: <Cpu className="w-5 h-5" />,
    gradient: 'from-sky-500 to-cyan-600',
    to: '/bitwise-calculator',
    category: 'learning',
    isNew: true,
  },
  {
    title: 'Big-O Cheat Sheet',
    description: 'Algorithm complexity reference guide',
    icon: <Target className="w-5 h-5" />,
    gradient: 'from-orange-500 to-red-600',
    to: '/big-o-cheatsheet',
    category: 'learning',
    isNew: true,
  },
  {
    title: 'Periodic Table',
    description: 'Interactive periodic table of elements',
    icon: <Atom className="w-5 h-5" />,
    gradient: 'from-violet-500 to-fuchsia-600',
    to: '/periodic-table',
    category: 'learning',
    isNew: true,
  },
  // Developer Tools (new batch)
  {
    title: 'Git Command Builder',
    description: 'Visual git command constructor with flags',
    icon: <GitMerge className="w-5 h-5" />,
    gradient: 'from-orange-500 to-red-600',
    to: '/git-command-builder',
    category: 'code',
    isNew: true,
  },
  {
    title: 'Chmod Calculator',
    description: 'Unix file permission calculator',
    icon: <Shield className="w-5 h-5" />,
    gradient: 'from-green-600 to-emerald-700',
    to: '/chmod-calculator',
    category: 'code',
    isNew: true,
  },
  {
    title: 'HTTP Status Reference',
    description: 'Complete HTTP status code reference',
    icon: <Globe className="w-5 h-5" />,
    gradient: 'from-blue-500 to-sky-600',
    to: '/http-status-reference',
    category: 'code',
    isNew: true,
  },
  {
    title: 'Code Screenshot',
    description: 'Generate beautiful code screenshots',
    icon: <CodeIcon className="w-5 h-5" />,
    gradient: 'from-purple-600 to-pink-600',
    to: '/code-screenshot',
    category: 'code',
    isNew: true,
  },
  {
    title: 'SVG Editor',
    description: 'Edit SVG code with live preview',
    icon: <Pen className="w-5 h-5" />,
    gradient: 'from-teal-500 to-cyan-600',
    to: '/svg-editor',
    category: 'code',
    isNew: true,
  },
  {
    title: 'HTML/CSS Playground',
    description: 'Live HTML, CSS & JS playground',
    icon: <FileCode2 className="w-5 h-5" />,
    gradient: 'from-amber-500 to-yellow-600',
    to: '/html-css-playground',
    category: 'code',
    isNew: true,
  },
  {
    title: 'Code Formatter',
    description: 'Format & minify JSON, HTML, CSS, SQL, XML',
    icon: <Braces className="w-5 h-5" />,
    gradient: 'from-indigo-500 to-blue-600',
    to: '/code-formatter',
    category: 'code',
    isNew: true,
  },
  {
    title: 'Webhook Tester',
    description: 'Build & test HTTP requests, export cURL',
    icon: <Plug className="w-5 h-5" />,
    gradient: 'from-rose-500 to-red-600',
    to: '/webhook-tester',
    category: 'code',
    isNew: true,
  },
  {
    title: 'package.json Generator',
    description: 'Interactive package.json builder',
    icon: <Package className="w-5 h-5" />,
    gradient: 'from-green-500 to-emerald-600',
    to: '/package-json-generator',
    category: 'code',
    isNew: true,
  },
  {
    title: '.env Editor',
    description: 'Environment variable editor with groups',
    icon: <FileCode className="w-5 h-5" />,
    gradient: 'from-gray-500 to-slate-600',
    to: '/env-editor',
    category: 'code',
    isNew: true,
  },
  {
    title: 'ASCII Art Generator',
    description: 'Convert text to ASCII art',
    icon: <Type className="w-5 h-5" />,
    gradient: 'from-lime-500 to-green-600',
    to: '/ascii-art-generator',
    category: 'code',
    isNew: true,
  },
  {
    title: 'Network Port Reference',
    description: 'Common network ports reference',
    icon: <Network className="w-5 h-5" />,
    gradient: 'from-cyan-500 to-blue-600',
    to: '/network-port-reference',
    category: 'code',
    isNew: true,
  },
  {
    title: 'XML Formatter',
    description: 'Format, minify & validate XML',
    icon: <FileCode2 className="w-5 h-5" />,
    gradient: 'from-orange-500 to-amber-600',
    to: '/xml-formatter',
    category: 'data',
    isNew: true,
  },
  {
    title: 'JSON/CSV Converter',
    description: 'Convert between JSON and CSV formats',
    icon: <ArrowRightLeft className="w-5 h-5" />,
    gradient: 'from-blue-500 to-indigo-600',
    to: '/json-csv-converter',
    category: 'data',
    isNew: true,
  },
  {
    title: 'Encoding Converter',
    description: 'Base64, URL, HTML, Unicode encoding',
    icon: <Lock className="w-5 h-5" />,
    gradient: 'from-violet-500 to-purple-600',
    to: '/encoding-converter',
    category: 'utils',
    isNew: true,
  },
  // Office & Productivity Tools (new batch)
  {
    title: 'Gantt Chart',
    description: 'Create project timelines & track progress',
    icon: <BarChart3 className="w-5 h-5" />,
    gradient: 'from-blue-500 to-cyan-600',
    to: '/gantt-chart',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Mind Map',
    description: 'Create visual mind maps & diagrams',
    icon: <GitBranch className="w-5 h-5" />,
    gradient: 'from-purple-500 to-pink-600',
    to: '/mind-map',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Presentation Timer',
    description: 'Timer with sections for presentations',
    icon: <Presentation className="w-5 h-5" />,
    gradient: 'from-indigo-500 to-violet-600',
    to: '/presentation-timer',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Meeting Scheduler',
    description: 'Find overlapping availability across timezones',
    icon: <Clock className="w-5 h-5" />,
    gradient: 'from-sky-500 to-blue-600',
    to: '/meeting-scheduler',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Email Template Builder',
    description: 'Build HTML email templates visually',
    icon: <Mail className="w-5 h-5" />,
    gradient: 'from-pink-500 to-rose-600',
    to: '/email-template-builder',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Habit Tracker',
    description: '30-day habit tracking with streaks',
    icon: <Target className="w-5 h-5" />,
    gradient: 'from-green-500 to-emerald-600',
    to: '/habit-tracker',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Daily Planner',
    description: 'Hourly schedule with priorities',
    icon: <Calendar className="w-5 h-5" />,
    gradient: 'from-blue-500 to-indigo-600',
    to: '/daily-planner',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Whiteboard',
    description: 'Freeform drawing canvas with shapes',
    icon: <Pen className="w-5 h-5" />,
    gradient: 'from-teal-500 to-cyan-600',
    to: '/whiteboard',
    category: 'office',
    isNew: true,
  },
  {
    title: 'CSV Viewer',
    description: 'View, sort & filter CSV data',
    icon: <Table2 className="w-5 h-5" />,
    gradient: 'from-emerald-500 to-green-600',
    to: '/csv-viewer',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Agenda Builder',
    description: 'Build structured meeting agendas',
    icon: <ClipboardList className="w-5 h-5" />,
    gradient: 'from-amber-500 to-yellow-600',
    to: '/agenda-builder',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Receipt Scanner',
    description: 'Digitize receipts with bill splitting',
    icon: <Receipt className="w-5 h-5" />,
    gradient: 'from-lime-500 to-green-600',
    to: '/receipt-scanner',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Loan Calculator',
    description: 'Calculate payments & amortization',
    icon: <Landmark className="w-5 h-5" />,
    gradient: 'from-violet-500 to-purple-600',
    to: '/loan-calculator',
    category: 'office',
    isNew: true,
  },
  {
    title: 'Spreadsheet Formula Ref',
    description: 'Excel/Sheets formula reference guide',
    icon: <FileSpreadsheet className="w-5 h-5" />,
    gradient: 'from-green-500 to-teal-600',
    to: '/spreadsheet-formula-ref',
    category: 'office',
    isNew: true,
  },
  // General Utility Tools (new batch)
  {
    title: 'Scientific Calculator',
    description: 'Advanced calculator with trig & functions',
    icon: <Calculator className="w-5 h-5" />,
    gradient: 'from-orange-500 to-red-600',
    to: '/scientific-calculator',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Barcode Generator',
    description: 'Generate QR codes & barcodes',
    icon: <Barcode className="w-5 h-5" />,
    gradient: 'from-cyan-500 to-teal-600',
    to: '/barcode-generator',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Text Diff & Merger',
    description: 'Compare & merge text with LCS diff',
    icon: <GitCompareArrows className="w-5 h-5" />,
    gradient: 'from-amber-500 to-orange-600',
    to: '/text-diff-merger',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Morse Code Converter',
    description: 'Encode/decode Morse code with audio',
    icon: <Radio className="w-5 h-5" />,
    gradient: 'from-yellow-500 to-amber-600',
    to: '/morse-code-converter',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'OCR Tool',
    description: 'Extract text from images',
    icon: <ScanText className="w-5 h-5" />,
    gradient: 'from-rose-500 to-red-600',
    to: '/ocr-tool',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Color Blindness Simulator',
    description: 'Test color accessibility for all vision types',
    icon: <Eye className="w-5 h-5" />,
    gradient: 'from-purple-500 to-violet-600',
    to: '/color-blindness-simulator',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Font Preview',
    description: 'Preview & compare fonts with custom text',
    icon: <Type className="w-5 h-5" />,
    gradient: 'from-pink-500 to-rose-600',
    to: '/font-preview',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Aspect Ratio Calculator',
    description: 'Calculate & convert aspect ratios',
    icon: <Monitor className="w-5 h-5" />,
    gradient: 'from-sky-500 to-blue-600',
    to: '/aspect-ratio-calculator',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Readability Analyzer',
    description: 'Analyze text readability & grade level',
    icon: <BookOpen className="w-5 h-5" />,
    gradient: 'from-emerald-500 to-green-600',
    to: '/readability-analyzer',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Privacy Redactor',
    description: 'Remove emails, phones, SSNs from text',
    icon: <ShieldCheck className="w-5 h-5" />,
    gradient: 'from-red-500 to-rose-600',
    to: '/privacy-redactor',
    category: 'utils',
    isNew: true,
  },
  // ============ DevOps & Infrastructure (new batch) ============
  {
    title: 'Helm Chart Builder',
    description: 'Build Kubernetes Helm charts visually',
    icon: <Ship className="w-5 h-5" />,
    gradient: 'from-blue-500 to-cyan-600',
    to: '/helm-chart-builder',
    category: 'devops',
    isNew: true,
  },
  {
    title: 'Ansible Playbook Builder',
    description: 'Generate Ansible playbooks & roles',
    icon: <Play className="w-5 h-5" />,
    gradient: 'from-red-500 to-orange-600',
    to: '/ansible-playbook-builder',
    category: 'devops',
    isNew: true,
  },
  {
    title: 'Prometheus Query Builder',
    description: 'Build PromQL queries visually',
    icon: <Activity className="w-5 h-5" />,
    gradient: 'from-orange-500 to-red-600',
    to: '/prometheus-query-builder',
    category: 'devops',
    isNew: true,
  },
  {
    title: 'Grafana Dashboard Builder',
    description: 'Design Grafana dashboards as JSON',
    icon: <LayoutDashboard className="w-5 h-5" />,
    gradient: 'from-amber-500 to-orange-600',
    to: '/grafana-dashboard-builder',
    category: 'devops',
    isNew: true,
  },
  {
    title: 'Vagrant File Builder',
    description: 'Generate Vagrantfiles for VMs',
    icon: <Box className="w-5 h-5" />,
    gradient: 'from-blue-400 to-indigo-500',
    to: '/vagrant-file-builder',
    category: 'devops',
    isNew: true,
  },
  {
    title: 'Systemd Service Builder',
    description: 'Create systemd unit files',
    icon: <Settings className="w-5 h-5" />,
    gradient: 'from-slate-500 to-gray-600',
    to: '/systemd-service-builder',
    category: 'devops',
    isNew: true,
  },
  {
    title: 'Shell Script Generator',
    description: 'Generate bash scripts with best practices',
    icon: <Terminal className="w-5 h-5" />,
    gradient: 'from-green-500 to-emerald-600',
    to: '/shell-script-generator',
    category: 'devops',
    isNew: true,
  },
  {
    title: 'Kafka Config Builder',
    description: 'Apache Kafka configuration generator',
    icon: <MessageSquare className="w-5 h-5" />,
    gradient: 'from-gray-600 to-slate-700',
    to: '/kafka-config-builder',
    category: 'devops',
    isNew: true,
  },
  {
    title: 'RabbitMQ Config Builder',
    description: 'RabbitMQ configuration generator',
    icon: <MessageSquare className="w-5 h-5" />,
    gradient: 'from-orange-500 to-amber-600',
    to: '/rabbitmq-config-builder',
    category: 'devops',
    isNew: true,
  },
  {
    title: 'Nginx Location Tester',
    description: 'Test nginx location block matching',
    icon: <Server className="w-5 h-5" />,
    gradient: 'from-green-600 to-teal-700',
    to: '/nginx-location-tester',
    category: 'devops',
    isNew: true,
  },
  {
    title: '.htaccess Generator',
    description: 'Generate Apache .htaccess rules',
    icon: <FileSearch className="w-5 h-5" />,
    gradient: 'from-red-600 to-rose-700',
    to: '/htaccess-generator',
    category: 'devops',
    isNew: true,
  },
  // ============ Code Converters (new batch) ============
  {
    title: 'cURL to Code',
    description: 'Convert cURL commands to code',
    icon: <ArrowRightLeft className="w-5 h-5" />,
    gradient: 'from-violet-500 to-purple-600',
    to: '/curl-to-code',
    category: 'converter',
    isNew: true,
  },
  {
    title: 'HTML to JSX',
    description: 'Convert HTML to React JSX',
    icon: <CodeIcon className="w-5 h-5" />,
    gradient: 'from-cyan-500 to-blue-600',
    to: '/html-to-jsx',
    category: 'converter',
    isNew: true,
  },
  {
    title: 'CSS to Tailwind',
    description: 'Convert CSS to Tailwind classes',
    icon: <Brush className="w-5 h-5" />,
    gradient: 'from-sky-500 to-cyan-600',
    to: '/css-to-tailwind',
    category: 'converter',
    isNew: true,
  },
  {
    title: 'JSON to TypeScript',
    description: 'Generate TS interfaces from JSON',
    icon: <FileCode className="w-5 h-5" />,
    gradient: 'from-blue-600 to-indigo-700',
    to: '/json-to-typescript',
    category: 'converter',
    isNew: true,
  },
  {
    title: 'JSON Schema Generator',
    description: 'Generate JSON Schema from data',
    icon: <Braces className="w-5 h-5" />,
    gradient: 'from-amber-500 to-orange-600',
    to: '/json-schema-generator',
    category: 'converter',
    isNew: true,
  },
  {
    title: 'SQL to NoSQL',
    description: 'Convert SQL queries to MongoDB',
    icon: <Database className="w-5 h-5" />,
    gradient: 'from-green-500 to-teal-600',
    to: '/sql-to-nosql',
    category: 'converter',
    isNew: true,
  },
  {
    title: 'Protobuf Builder',
    description: 'Build Protocol Buffer definitions',
    icon: <FileCode2 className="w-5 h-5" />,
    gradient: 'from-indigo-500 to-purple-600',
    to: '/protobuf-builder',
    category: 'converter',
    isNew: true,
  },
  // ============ Security & Auth (new batch) ============
  {
    title: 'AWS IAM Policy Builder',
    description: 'Build AWS IAM policies visually',
    icon: <Shield className="w-5 h-5" />,
    gradient: 'from-amber-500 to-orange-600',
    to: '/aws-iam-policy-builder',
    category: 'security',
    isNew: true,
  },
  {
    title: 'CORS Config Builder',
    description: 'Configure CORS headers & policies',
    icon: <Globe className="w-5 h-5" />,
    gradient: 'from-blue-500 to-indigo-600',
    to: '/cors-config-builder',
    category: 'security',
    isNew: true,
  },
  {
    title: 'CSP Header Builder',
    description: 'Build Content Security Policy headers',
    icon: <ShieldCheck className="w-5 h-5" />,
    gradient: 'from-green-500 to-emerald-600',
    to: '/csp-header-builder',
    category: 'security',
    isNew: true,
  },
  {
    title: 'OAuth2 Flow Visualizer',
    description: 'Visualize OAuth2 authentication flows',
    icon: <Key className="w-5 h-5" />,
    gradient: 'from-purple-500 to-violet-600',
    to: '/oauth2-flow-visualizer',
    category: 'security',
    isNew: true,
  },
  {
    title: 'RBAC Designer',
    description: 'Design role-based access control',
    icon: <Users className="w-5 h-5" />,
    gradient: 'from-indigo-500 to-blue-600',
    to: '/rbac-designer',
    category: 'security',
    isNew: true,
  },
  {
    title: 'Secret Generator',
    description: 'Generate API keys, tokens & secrets',
    icon: <Zap className="w-5 h-5" />,
    gradient: 'from-yellow-500 to-amber-600',
    to: '/secret-generator',
    category: 'security',
    isNew: true,
  },
  {
    title: 'Data Masking Tool',
    description: 'Mask sensitive data in datasets',
    icon: <EyeOff className="w-5 h-5" />,
    gradient: 'from-red-500 to-rose-600',
    to: '/data-masking-tool',
    category: 'security',
    isNew: true,
  },
  // ============ Frontend & Design (new batch) ============
  {
    title: 'Meta Tag Generator',
    description: 'Generate SEO & social meta tags',
    icon: <Tag className="w-5 h-5" />,
    gradient: 'from-pink-500 to-rose-600',
    to: '/meta-tag-generator',
    category: 'frontend',
    isNew: true,
  },
  {
    title: 'Favicon Generator',
    description: 'Generate favicons from text or emoji',
    icon: <ImageIcon className="w-5 h-5" />,
    gradient: 'from-purple-500 to-fuchsia-600',
    to: '/favicon-generator',
    category: 'frontend',
    isNew: true,
  },
  {
    title: 'Robots.txt Generator',
    description: 'Generate robots.txt for web crawlers',
    icon: <Bot className="w-5 h-5" />,
    gradient: 'from-slate-500 to-gray-600',
    to: '/robots-txt-generator',
    category: 'frontend',
    isNew: true,
  },
  {
    title: 'CSS Grid Generator',
    description: 'Visual CSS Grid layout builder',
    icon: <LayoutGrid className="w-5 h-5" />,
    gradient: 'from-cyan-500 to-blue-600',
    to: '/css-grid-generator',
    category: 'frontend',
    isNew: true,
  },
  {
    title: 'CSS Flexbox Playground',
    description: 'Interactive CSS Flexbox designer',
    icon: <Move className="w-5 h-5" />,
    gradient: 'from-violet-500 to-purple-600',
    to: '/css-flexbox-playground',
    category: 'frontend',
    isNew: true,
  },
  {
    title: 'Animation Builder',
    description: 'Build CSS animations visually',
    icon: <Wand2 className="w-5 h-5" />,
    gradient: 'from-pink-500 to-fuchsia-600',
    to: '/animation-builder',
    category: 'frontend',
    isNew: true,
  },
  {
    title: 'Responsive Breakpoint Tester',
    description: 'Test responsive designs at breakpoints',
    icon: <Smartphone className="w-5 h-5" />,
    gradient: 'from-green-500 to-teal-600',
    to: '/responsive-breakpoint-tester',
    category: 'frontend',
    isNew: true,
  },
  {
    title: 'Image to Base64',
    description: 'Convert images to Base64 strings',
    icon: <ImageIcon className="w-5 h-5" />,
    gradient: 'from-amber-500 to-yellow-600',
    to: '/image-to-base64',
    category: 'frontend',
    isNew: true,
  },
  // ============ Data & Database (new batch) ============
  {
    title: 'Rate Limit Calculator',
    description: 'Calculate API rate limiting strategies',
    icon: <Gauge className="w-5 h-5" />,
    gradient: 'from-orange-500 to-red-600',
    to: '/rate-limit-calculator',
    category: 'data',
    isNew: true,
  },
  {
    title: 'API Endpoint Planner',
    description: 'Plan RESTful API endpoint structure',
    icon: <Route className="w-5 h-5" />,
    gradient: 'from-blue-500 to-indigo-600',
    to: '/api-endpoint-planner',
    category: 'data',
    isNew: true,
  },
  {
    title: 'Cassandra CQL Builder',
    description: 'Build Cassandra CQL queries',
    icon: <Database className="w-5 h-5" />,
    gradient: 'from-blue-400 to-cyan-500',
    to: '/cassandra-cql-builder',
    category: 'data',
    isNew: true,
  },
  {
    title: 'DynamoDB Table Designer',
    description: 'Design DynamoDB tables & indexes',
    icon: <DatabaseZap className="w-5 h-5" />,
    gradient: 'from-amber-500 to-orange-600',
    to: '/dynamodb-table-designer',
    category: 'data',
    isNew: true,
  },
  {
    title: 'Database Index Advisor',
    description: 'Get index recommendations for queries',
    icon: <SearchIcon className="w-5 h-5" />,
    gradient: 'from-green-500 to-emerald-600',
    to: '/database-index-advisor',
    category: 'data',
    isNew: true,
  },
  // ============ Project & Workflow (new batch) ============
  {
    title: 'Conventional Commit Builder',
    description: 'Build conventional commit messages',
    icon: <GitCommitHorizontal className="w-5 h-5" />,
    gradient: 'from-violet-500 to-purple-600',
    to: '/conventional-commit-builder',
    category: 'code',
    isNew: true,
  },
  {
    title: 'Changelog Generator',
    description: 'Generate CHANGELOG from commits',
    icon: <FileText className="w-5 h-5" />,
    gradient: 'from-blue-500 to-indigo-600',
    to: '/changelog-generator',
    category: 'code',
    isNew: true,
  },
  {
    title: 'README Generator',
    description: 'Generate README.md with templates',
    icon: <FileText className="w-5 h-5" />,
    gradient: 'from-emerald-500 to-green-600',
    to: '/readme-generator',
    category: 'code',
    isNew: true,
  },
  {
    title: 'License Picker',
    description: 'Compare & choose open source licenses',
    icon: <Scale className="w-5 h-5" />,
    gradient: 'from-amber-500 to-yellow-600',
    to: '/license-picker',
    category: 'code',
    isNew: true,
  },
  {
    title: 'SemVer Calculator',
    description: 'Semantic versioning range calculator',
    icon: <Tag className="w-5 h-5" />,
    gradient: 'from-cyan-500 to-teal-600',
    to: '/semver-calculator',
    category: 'code',
    isNew: true,
  },
  {
    title: 'Sprint Planner',
    description: 'Plan sprints with story points & velocity',
    icon: <KanbanSquare className="w-5 h-5" />,
    gradient: 'from-indigo-500 to-blue-600',
    to: '/sprint-planner',
    category: 'office',
    isNew: true,
  },
  // ============ Reference & Learning (new batch) ============
  {
    title: 'Dependency Matrix',
    description: 'Visualize project dependency relationships',
    icon: <Grid3x3 className="w-5 h-5" />,
    gradient: 'from-purple-500 to-violet-600',
    to: '/dependency-matrix',
    category: 'reference',
    isNew: true,
  },
  {
    title: 'Linux Command Reference',
    description: 'Searchable Linux command cheat sheet',
    icon: <Terminal className="w-5 h-5" />,
    gradient: 'from-green-600 to-emerald-700',
    to: '/linux-command-reference',
    category: 'reference',
    isNew: true,
  },
  {
    title: 'Docker Command Reference',
    description: 'Complete Docker command reference',
    icon: <Container className="w-5 h-5" />,
    gradient: 'from-blue-500 to-cyan-600',
    to: '/docker-command-reference',
    category: 'reference',
    isNew: true,
  },
  {
    title: 'Design Patterns Reference',
    description: 'GoF design patterns with examples',
    icon: <Blocks className="w-5 h-5" />,
    gradient: 'from-orange-500 to-amber-600',
    to: '/design-patterns-reference',
    category: 'reference',
    isNew: true,
  },
  {
    title: 'Keyboard Shortcut Ref',
    description: 'IDE & app keyboard shortcuts',
    icon: <Keyboard className="w-5 h-5" />,
    gradient: 'from-pink-500 to-rose-600',
    to: '/keyboard-shortcut-reference',
    category: 'reference',
    isNew: true,
  },
  {
    title: 'PlantUML Editor',
    description: 'Write & preview PlantUML diagrams',
    icon: <Workflow className="w-5 h-5" />,
    gradient: 'from-teal-500 to-cyan-600',
    to: '/plantuml-editor',
    category: 'code',
    isNew: true,
  },
  {
    title: 'Log Format Parser',
    description: 'Parse & analyze log file formats',
    icon: <FileSearch className="w-5 h-5" />,
    gradient: 'from-yellow-500 to-amber-600',
    to: '/log-format-parser',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Crontab Validator',
    description: 'Validate & explain crontab expressions',
    icon: <Clock className="w-5 h-5" />,
    gradient: 'from-indigo-500 to-violet-600',
    to: '/crontab-validator',
    category: 'utils',
    isNew: true,
  },
  {
    title: 'Grok Pattern Tester',
    description: 'Parse logs with Grok patterns (Logstash/ELK)',
    icon: <FileSearch className="w-5 h-5" />,
    gradient: 'from-orange-500 to-red-600',
    to: '/grok-parser',
    category: 'data',
    isNew: true,
  },
  {
    title: 'Java Code Generator',
    description: 'Java 21 + Spring Boot 3.5 template factory',
    icon: <CodeIcon className="w-5 h-5" />,
    gradient: 'from-indigo-500 to-purple-600',
    to: '/java-code-generator',
    category: 'code',
    isNew: true,
  },
  // Government Forms & Calculators
  {
    title: 'LTC Claim Calculator',
    description: 'Leave Travel Concession claim form (GAR-14C) with entitlements',
    icon: <Landmark className="w-5 h-5" />,
    gradient: 'from-emerald-500 to-teal-600',
    to: '/ltc-claim-calculator',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'TA/DA Calculator',
    description: 'Tour TA/DA bill (GAR-14A) with journey legs & DA rates',
    icon: <Receipt className="w-5 h-5" />,
    gradient: 'from-blue-500 to-cyan-600',
    to: '/ta-da-calculator',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'Transfer TA Calculator',
    description: 'Transfer travelling allowance (GAR-14B) with weight entitlements',
    icon: <Move className="w-5 h-5" />,
    gradient: 'from-indigo-500 to-blue-600',
    to: '/transfer-ta-calculator',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'Festival Advance',
    description: 'Festival advance application & recovery schedule calculator',
    icon: <Calendar className="w-5 h-5" />,
    gradient: 'from-orange-500 to-amber-600',
    to: '/festival-advance-calc',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'Pay Fixation Calculator',
    description: 'Pay fixation on promotion/MACP with Option 1 vs 2 comparison',
    icon: <Calculator className="w-5 h-5" />,
    gradient: 'from-green-500 to-emerald-600',
    to: '/pay-fixation-calculator',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: '7th CPC Pay Matrix',
    description: 'Interactive pay level matrix browser for Levels 1-18',
    icon: <Grid3x3 className="w-5 h-5" />,
    gradient: 'from-teal-500 to-green-600',
    to: '/pay-level-matrix',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'Govt Salary Slip',
    description: 'Monthly salary slip generator with all earnings & deductions',
    icon: <DollarSign className="w-5 h-5" />,
    gradient: 'from-cyan-500 to-blue-600',
    to: '/govt-salary-slip',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'DA Rate Lookup',
    description: 'DA rate history, calculator & arrear computation',
    icon: <BarChart3 className="w-5 h-5" />,
    gradient: 'from-violet-500 to-purple-600',
    to: '/da-rate-lookup',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'Pension & Gratuity',
    description: 'Pension, DCRG & commutation calculator with age-based factors',
    icon: <Landmark className="w-5 h-5" />,
    gradient: 'from-purple-500 to-indigo-600',
    to: '/pension-gratuity-calculator',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'Retirement Planner',
    description: 'Unified retirement benefits dashboard with total corpus',
    icon: <Hourglass className="w-5 h-5" />,
    gradient: 'from-rose-500 to-pink-600',
    to: '/retirement-planner',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'GPF Calculator',
    description: 'GPF balance projection, advance application & Form 3A/4',
    icon: <Wallet className="w-5 h-5" />,
    gradient: 'from-amber-500 to-orange-600',
    to: '/gpf-calculator',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'NPS Tracker',
    description: 'NPS contribution tracker, corpus projection & annuity calculator',
    icon: <Target className="w-5 h-5" />,
    gradient: 'from-sky-500 to-blue-600',
    to: '/nps-tracker',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'Income Tax Calculator',
    description: 'Old vs New regime comparison with Form 12BB generator',
    icon: <Scale className="w-5 h-5" />,
    gradient: 'from-red-500 to-rose-600',
    to: '/income-tax-calculator',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'HRA Calculator',
    description: 'HRA exemption calculation & rent receipt generator',
    icon: <Receipt className="w-5 h-5" />,
    gradient: 'from-pink-500 to-rose-600',
    to: '/hra-calculator',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'CGHS Claim Form',
    description: 'Medical reimbursement MRC(S) form with bill items & checklist',
    icon: <ClipboardList className="w-5 h-5" />,
    gradient: 'from-red-500 to-orange-600',
    to: '/cghs-claim-form',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'GIS/CGEGIS Calculator',
    description: 'Group insurance savings fund & insurance cover calculator',
    icon: <Shield className="w-5 h-5" />,
    gradient: 'from-teal-500 to-cyan-600',
    to: '/gis-cgegis-calculator',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'Leave Manager',
    description: 'Leave balance tracker, application form & encashment calculator',
    icon: <Calendar className="w-5 h-5" />,
    gradient: 'from-yellow-500 to-amber-600',
    to: '/leave-manager',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'CEA Reimbursement',
    description: 'Children Education Allowance form (Annexure-I) with hostel subsidy',
    icon: <GraduationCap className="w-5 h-5" />,
    gradient: 'from-orange-500 to-yellow-600',
    to: '/cea-reimbursement',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'Property Return Form',
    description: 'Annual immovable property return under CCS Conduct Rules',
    icon: <FileText className="w-5 h-5" />,
    gradient: 'from-fuchsia-500 to-pink-600',
    to: '/property-return-form',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'Govt Forms Reference',
    description: 'Searchable directory of 44+ government forms with categories',
    icon: <BookOpen className="w-5 h-5" />,
    gradient: 'from-emerald-500 to-green-600',
    to: '/govt-form-reference',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'Form → Code Generator',
    description: 'Build form fields visually, generate React + MUI app code with print',
    icon: <Wand2 className="w-5 h-5" />,
    gradient: 'from-violet-500 to-fuchsia-600',
    to: '/form-to-code-generator',
    category: 'govtforms',
    isNew: true,
  },
  {
    title: 'Dynamic Form Creator',
    description: 'Build custom forms dynamically, fill & print — data persists in localStorage',
    icon: <FormInput className="w-5 h-5" />,
    gradient: 'from-purple-500 to-indigo-600',
    to: '/dynamic-form-creator',
    category: 'utils',
    isNew: true,
  },
];

const ToolCard = ({ tool }: { tool: Tool }) => (
  <Link
    to={tool.to}
    className="group relative flex items-center gap-3 p-3 rounded-xl bg-gray-800/40 border border-gray-700/40 hover:bg-gray-800/70 hover:border-gray-600/60 transition-all duration-200 hover:shadow-lg hover:shadow-black/20"
  >
    {/* Icon */}
    <div
      className={`flex-shrink-0 w-10 h-10 rounded-lg bg-gradient-to-br ${tool.gradient} flex items-center justify-center text-white shadow-lg`}
    >
      {tool.icon}
    </div>

    {/* Content */}
    <div className="flex-1 min-w-0">
      <div className="flex items-center gap-2">
        <h3 className="text-sm font-medium text-white truncate group-hover:text-blue-400 transition-colors">
          {tool.title}
        </h3>
        {tool.isNew && (
          <span className="flex-shrink-0 text-[10px] font-semibold bg-blue-500/20 text-blue-400 px-1.5 py-0.5 rounded">
            NEW
          </span>
        )}
      </div>
      <p className="text-xs text-gray-500 truncate">{tool.description}</p>
    </div>
  </Link>
);

export default function Home() {
  const [activeCategory, setActiveCategory] = useState('all');
  const [searchQuery, setSearchQuery] = useState('');

  const filteredTools = tools.filter((tool) => {
    const matchesCategory = activeCategory === 'all' || tool.category === activeCategory;
    const matchesSearch =
      searchQuery === '' ||
      tool.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      tool.description.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  const newToolsCount = tools.filter((t) => t.isNew).length;

  return (
    <div className="min-h-screen bg-gray-950">
      {/* Subtle background */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-blue-500/5 rounded-full blur-3xl" />
        <div className="absolute bottom-0 right-1/4 w-[500px] h-[500px] bg-purple-500/5 rounded-full blur-3xl" />
      </div>

      <div className="relative z-10 max-w-6xl mx-auto px-4 py-8">
        {/* Compact Header */}
        <header className="text-center mb-8">
          <h1 className="text-3xl font-bold text-white mb-2">
            Dev Tools{' '}
            <span className="bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
              Hub
            </span>
          </h1>
          <p className="text-gray-500 text-sm">
            {tools.length} tools for development, data & infrastructure
          </p>
        </header>

        {/* Search & Filter Bar */}
        <div className="flex flex-col sm:flex-row gap-3 mb-6">
          {/* Search */}
          <div className="relative flex-1">
            <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500" />
            <input
              type="text"
              placeholder="Search tools..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-4 py-2 bg-gray-800/50 border border-gray-700/50 rounded-lg text-sm text-white placeholder-gray-500 focus:outline-none focus:border-blue-500/50 focus:ring-1 focus:ring-blue-500/20 transition-all"
            />
          </div>

          {/* Category Filter */}
          <div className="flex gap-1.5 overflow-x-auto pb-1 scrollbar-hide">
            {categories.map((cat) => (
              <button
                key={cat.id}
                onClick={() => setActiveCategory(cat.id)}
                className={`flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium whitespace-nowrap transition-all ${
                  activeCategory === cat.id
                    ? 'bg-blue-500/20 text-blue-400 border border-blue-500/30'
                    : 'bg-gray-800/40 text-gray-400 border border-gray-700/40 hover:bg-gray-800/60 hover:text-gray-300'
                }`}
              >
                {cat.icon}
                {cat.label}
              </button>
            ))}
          </div>
        </div>

        {/* Stats Bar */}
        <div className="flex items-center justify-between mb-6 px-1">
          <div className="flex items-center gap-4 text-xs text-gray-500">
            <span className="flex items-center gap-1.5">
              <Filter className="w-3.5 h-3.5" />
              {filteredTools.length} tools
            </span>
            <span className="flex items-center gap-1.5">
              <Sparkles className="w-3.5 h-3.5 text-blue-400" />
              {newToolsCount} new
            </span>
          </div>
        </div>

        {/* Tools Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-3">
          {filteredTools.map((tool) => (
            <ToolCard key={tool.to} tool={tool} />
          ))}
        </div>

        {/* Empty State */}
        {filteredTools.length === 0 && (
          <div className="text-center py-16">
            <SearchIcon className="w-12 h-12 text-gray-700 mx-auto mb-4" />
            <p className="text-gray-500">No tools found matching your search</p>
            <button
              onClick={() => {
                setSearchQuery('');
                setActiveCategory('all');
              }}
              className="mt-4 text-blue-400 text-sm hover:underline"
            >
              Clear filters
            </button>
          </div>
        )}

        {/* Footer */}
        <footer className="mt-12 text-center text-gray-600 text-xs">
          <p>Built with React 19 + TypeScript + Vite + Tailwind CSS</p>
        </footer>
      </div>
    </div>
  );
}